import type { ReaderBlock } from "./types";

export const readerBlocks2: ReaderBlock[] = [
  {"type":"h1","text":"Problema directo"},
  {"type":"table","rows":[["011","Si tus anuncios tienen vistas pero nadie consulta, esto te interesa."]]},
  {"type":"table","rows":[["012","¿Publicás y sentís que nadie se detiene a mirar?"]]},
  {"type":"table","rows":[["013","Si [problema específico] te está costando ventas, empezá por acá."]]},
  {"type":"table","rows":[["014","El error no es que tu producto sea malo: puede ser cómo lo estás mostrando."]]},
  {"type":"table","rows":[["015","Si la gente pregunta precio y desaparece, probá este enfoque."]]},
  {"type":"table","rows":[["016","¿Tus videos parecen publicidad desde el primer segundo? Ese puede ser el problema."]]},
  {"type":"table","rows":[["017","Si nadie llega al final de tu video, no arregles el CTA todavía."]]},
  {"type":"table","rows":[["018","Si tu anuncio necesita 10 segundos para explicar de qué trata, ya arrancó tarde."]]},
  {"type":"table","rows":[["019","No necesitás más ideas: necesitás una mejor apertura."]]},
  {"type":"table","rows":[["020","Si estás cambiando público, precio y anuncio al mismo tiempo, nunca vas a saber qué falló."]]},
  {"type":"kicker","text":"HOOKS 021-030"},
  {"type":"h1","text":"Deseo / transformación"},
  {"type":"table","rows":[["021","Imaginate que tu próximo anuncio haga que la persona quiera seguir mirando sin que se lo pidas."]]},
  {"type":"table","rows":[["022","Así se ve pasar de “nadie pregunta” a tener conversaciones reales por [producto/servicio]."]]},
  {"type":"table","rows":[["023","Cómo hacer que [resultado] se entienda en menos de 5 segundos."]]},
  {"type":"table","rows":[["024","La forma más simple de mostrar [beneficio] sin explicarlo durante un minuto."]]},
  {"type":"table","rows":[["025","Un anuncio debería hacer que la persona piense: “esto es para mí”. Así se construye."]]},
  {"type":"table","rows":[["026","Cómo convertir una característica aburrida en un beneficio que se siente."]]},
  {"type":"table","rows":[["027","Si querés que recuerden tu oferta, hacé que primero sientan esto."]]},
  {"type":"table","rows":[["028","No vendas [producto]. Vendé el momento en que [resultado deseado]."]]},
  {"type":"table","rows":[["029","El cambio de enfoque que hace que [oferta] se sienta mucho más deseable."]]},
  {"type":"table","rows":[["030","Antes de pedir una compra, hacé visible el después que la persona quiere."]]},
  {"type":"kicker","text":"HOOKS 031-040"},
  {"type":"h1","text":"Contrario / mito"},
  {"type":"table","rows":[["031","“Tenés que mostrar el logo primero” puede ser una pésima idea para este tipo de anuncio."]]},
  {"type":"table","rows":[["032","Más producción no siempre significa más atención."]]},
  {"type":"table","rows":[["033","El video más lindo no necesariamente es el que más vende."]]},
  {"type":"table","rows":[["034","No necesitás hablar más rápido: necesitás eliminar lo que no importa."]]},
  {"type":"table","rows":[["035","Un descuento no arregla un anuncio que nadie mira."]]},
  {"type":"table","rows":[["036","Más información puede bajar tus resultados si la ponés demasiado pronto."]]},
  {"type":"table","rows":[["037","No siempre conviene empezar diciendo quién sos."]]},
  {"type":"table","rows":[["038","La viralidad no empieza con una tendencia: empieza con una tensión."]]},
  {"type":"table","rows":[["039","No copies el anuncio de tu competencia. Copiá el patrón que lo hace interesante."]]},
  {"type":"table","rows":[["040","Un buen CTA no salva un video que perdió al público en el segundo dos."]]},
  {"type":"kicker","text":"HOOKS 041-050"},
  {"type":"h1","text":"Demostración / prueba visual"},
  {"type":"table","rows":[["041","Mirá la diferencia entre mostrar [producto] así... y mostrarlo así."]]},
  {"type":"table","rows":[["042","Esto es [producto] resolviendo [problema] en tiempo real."]]},
  {"type":"table","rows":[["043","En lugar de decirte que funciona, te lo muestro."]]},
  {"type":"table","rows":[["044","Veamos cuánto tarda [producto/proceso] en lograr [microresultado]."]]},
  {"type":"table","rows":[["045","Este es el antes. Este es el después. Y esto cambió en el medio."]]},
  {"type":"table","rows":[["046","Poné atención a lo que pasa cuando [acción demostrable]."]]},
  {"type":"table","rows":[["047","Probemos [objeción] para ver si realmente pasa."]]},
  {"type":"table","rows":[["048","Tres segundos para entender por qué [característica] importa."]]},
  {"type":"table","rows":[["049","Así se ve [beneficio] sin filtros ni edición."]]},
  {"type":"table","rows":[["050","Si dudás de [promesa], mirá esta prueba."]]},
  {"type":"kicker","text":"HOOKS 051-060"},
  {"type":"h1","text":"Error / advertencia"},
  {"type":"table","rows":[["051","No hagas otro anuncio de [categoría] antes de corregir esto."]]},
  {"type":"table","rows":[["052","Este error hace que tu video parezca un anuncio antes de que la persona entienda el valor."]]},
  {"type":"table","rows":[["053","Si abrís tu video con esta frase, probablemente estés perdiendo atención."]]},
  {"type":"table","rows":[["054","Tres cosas que sacaría de tu anuncio hoy mismo."]]},
  {"type":"table","rows":[["055","El error más caro no está en Ads Manager: está en el creativo."]]},
  {"type":"table","rows":[["056","No pongas cinco beneficios en el primer segundo. Elegí uno."]]},
  {"type":"table","rows":[["057","Si tu video empieza lento, la persona no va a esperar “la parte buena”."]]},
  {"type":"table","rows":[["058","No escondas el producto hasta el final si el producto es lo interesante."]]},
  {"type":"table","rows":[["059","Una promesa enorme sin mecanismo suele sonar a humo."]]},
  {"type":"table","rows":[["060","No pruebes diez variables juntas. Así nunca aprendés qué funcionó."]]},
  {"type":"kicker","text":"HOOKS 061-070"},
  {"type":"h1","text":"Lista / número"},
  {"type":"table","rows":[["061","3 formas de hacer que [producto/servicio] se vea más deseable en video."]]},
  {"type":"table","rows":[["062","5 hooks que usaría si hoy tuviera que vender [categoría]."]]},
  {"type":"table","rows":[["063","3 señales de que tu anuncio pierde atención demasiado rápido."]]},
  {"type":"table","rows":[["064","4 ángulos para vender el mismo producto sin repetir el mensaje."]]},
  {"type":"table","rows":[["065","3 maneras de demostrar valor sin decir “somos los mejores”."]]},
  {"type":"table","rows":[["066","5 preguntas para encontrar una idea de anuncio en 10 minutos."]]},
  {"type":"table","rows":[["067","3 formas de convertir una objeción en el inicio del video."]]},
  {"type":"table","rows":[["068","4 tipos de prueba que podés mostrar aunque recién estés empezando."]]},
  {"type":"table","rows":[["069","3 cierres mejores que “comprá ahora”."]]},
  {"type":"table","rows":[["070","5 cosas que reviso antes de ponerle presupuesto a un anuncio."]]},
  {"type":"kicker","text":"HOOKS 071-080"},
  {"type":"h1","text":"Historia / confesión"},
  {"type":"table","rows":[["071","Pensé que necesitaba mejores anuncios. En realidad necesitaba una mejor idea."]]},
  {"type":"table","rows":[["072","El primer anuncio que hice para [oferta] fue un desastre por esta razón."]]},
  {"type":"table","rows":[["073","Estuve cambiando públicos hasta que entendí que el problema estaba en el video."]]},
  {"type":"table","rows":[["074","Esto es lo que aprendí después de ver decenas de anuncios de [industria]."]]},
  {"type":"table","rows":[["075","Una vez intenté explicar todo en 30 segundos. El resultado fue exactamente el contrario."]]},
  {"type":"table","rows":[["076","La mejor idea apareció cuando dejé de hablar del producto y hablé del momento."]]},
  {"type":"table","rows":[["077","Creía que el hook era una frase. Después entendí que también podía ser una imagen."]]},
  {"type":"table","rows":[["078","El anuncio empezó a mejorar cuando eliminé los primeros tres segundos."]]},
  {"type":"table","rows":[["079","No fue una transición ni un efecto. Fue este cambio de argumento."]]},
  {"type":"table","rows":[["080","La lección: la gente no comparte publicidad; comparte algo que le sirve, sorprende o representa."]]},
  {"type":"kicker","text":"HOOKS 081-090"},
  {"type":"h1","text":"Reto / participación"},
  {"type":"table","rows":[["081","Decime qué vendés y tratá de encontrar el beneficio en esta frase."]]},
  {"type":"table","rows":[["082","¿Cuál de estos dos anuncios mirarías hasta el final?"]]},
  {"type":"table","rows":[["083","Pausa el video: ¿qué cambiarías primero acá?"]]},
  {"type":"table","rows":[["084","Te desafío a explicar tu producto sin usar la palabra [palabra típica]."]]},
  {"type":"table","rows":[["085","¿Podés entender la oferta antes de que termine este contador?"]]},
  {"type":"table","rows":[["086","Elegí A o B: ¿qué apertura genera más curiosidad?"]]},
  {"type":"table","rows":[["087","Intentá detectar el error antes de que te lo muestre."]]},
  {"type":"table","rows":[["088","Si vendés [categoría], completá esta frase y tenés un hook."]]},
  {"type":"table","rows":[["089","Guardá esto y usalo la próxima vez que no sepas qué publicar."]]},
  {"type":"table","rows":[["090","Comentá tu rubro y convertí esta estructura en una idea para vos."]]}
];
