import type { ReaderBlock } from "./types";

export const readerBlocks5: ReaderBlock[] = [
  {"type":"h2","text":"10. Pattern mining"},
  {"type":"callout","text":"Te paso una lista de anuncios que vi: [NOTAS]. Extraé patrones de hook, ritmo, prueba, CTA y emoción. No copies frases; convertí los patrones en 10 ideas originales para [MI OFERTA]."},
  {"type":"h2","text":"11. Reescritura anti-publicidad"},
  {"type":"callout","text":"Reescribí este anuncio para que suene nativo, humano y directo: [COPY]. Eliminá lenguaje corporativo, introducciones, adjetivos vacíos y explicaciones redundantes. Mantené la oferta clara."},
  {"type":"h2","text":"12. Oferta en 5 segundos"},
  {"type":"callout","text":"Mi oferta es [OFERTA]. Creá 10 formas de explicarla en una sola frase que respondan: para quién es, qué resultado busca y qué mecanismo usa. Máximo 16 palabras."},
  {"type":"h2","text":"13. Diagnóstico creativo"},
  {"type":"callout","text":"Métricas/observaciones: [DATOS]. Ayudame a diagnosticar en orden: atención, retención, deseo, CTA, oferta y landing. No propongas cambiar todo; elegí la hipótesis más probable y un test de una sola variable."},
  {"type":"h2","text":"14. Guion antes/después"},
  {"type":"callout","text":"Creá 5 anuncios antes/después para [PRODUCTO/SERVICIO]. El “antes” debe ser una escena específica, el “después” una mejora observable y el puente debe explicar el mecanismo sin prometer resultados garantizados."},
  {"type":"h2","text":"15. Contenido de comentario"},
  {"type":"callout","text":"Estas son preguntas reales de clientes: [PREGUNTAS]. Convertí cada pregunta en un anuncio estilo respuesta a comentario: hook con la pregunta, respuesta de 1 frase, demostración o prueba y CTA."},
  {"type":"h2","text":"16. Local viral"},
  {"type":"callout","text":"Tengo un negocio local de [RUBRO] en [ZONA]. Dame 20 ideas de videos que puedan generar guardados, compartidos o visitas. Priorizá: POV, producto estrella, detrás de escena, ranking, secreto del lugar, comparación y recomendación."},
  {"type":"h2","text":"17. Profesional con credibilidad"},
  {"type":"callout","text":"Soy [PROFESION]. Generá 15 ideas de anuncios educativos que construyan confianza sin hacer promesas absolutas, sin diagnosticar casos individuales y sin usar miedo exagerado."},
  {"type":"h2","text":"18. Producto físico demo"},
  {"type":"callout","text":"Para [PRODUCTO], dame 20 microdemostraciones grabables con celular. Cada una debe mostrar una característica convirtiéndose en un beneficio visible en menos de 8 segundos."},
  {"type":"h2","text":"19. Oferta digital"},
  {"type":"callout","text":"Vendo [PRODUCTO DIGITAL]. Dame 15 ideas de anuncios que muestren el producto por dentro, el “momento de uso” y el resultado de organización/claridad que facilita, sin prometer ingresos garantizados."},
  {"type":"h2","text":"20. Director creativo semanal"},
  {"type":"callout","text":"Con esta oferta [OFERTA] y estos aprendizajes de la semana [APRENDIZAJES], diseñá una matriz de 12 creativos: 3 ángulos x 2 hooks x 2 formatos. Indicá qué variable mantiene fija cada test."},
  {"type":"kicker","text":"07  |  RESEARCH"},
  {"type":"h1","text":"Investigá patrones, no copies anuncios"},
  {"type":"p","text":"La investigación creativa sirve para responder: qué hooks aparecen, qué visuales se repiten, dónde llega la demostración, cómo cierra la pieza y qué emoción organiza la historia."},
  {"type":"h2","text":"Workflow de 20 minutos"},
  {"type":"bullet","text":"5 min: buscá anuncios de tu industria y de industrias con una compra parecida."},
  {"type":"bullet","text":"5 min: guardá 10 piezas sólo por el patrón, no porque “te gusten”."},
  {"type":"bullet","text":"5 min: anotá hook, visual inicial, tensión, prueba, CTA y duración aproximada."},
  {"type":"bullet","text":"5 min: convertí lo repetido en reglas abstractas y escribí ideas originales para tu oferta."},
  {"type":"callout","text":"Herramienta: TikTok Creative Center\nTop Ads permite explorar creatividades autorizadas de alto rendimiento y analizar señales como CTR, vistas de 2s/6s, CVR y momentos de interacción. Usalo para estudiar patrones, no para clonar piezas."},
  {"type":"callout","text":"Herramienta: Meta Ad Library\nLa biblioteca de anuncios permite ver anuncios que están corriendo en tecnologías de Meta. Es útil para observar oferta, frecuencia de mensajes, formatos y ángulos activos de una marca."},
  {"type":"kicker","text":"PLANTILLA"},
  {"type":"h1","text":"La ficha de pattern mining"},
  {"type":"table","rows":[["Hook verbal","________________________________________________________"]]},
  {"type":"table","rows":[["Hook visual","________________________________________________________"]]},
  {"type":"table","rows":[["Qué promete","________________________________________________________"]]},
  {"type":"table","rows":[["Qué tensión abre","________________________________________________________"]]},
  {"type":"table","rows":[["Qué muestra como prueba","________________________________________________________"]]},
  {"type":"table","rows":[["Cambio visual / ritmo","________________________________________________________"]]},
  {"type":"table","rows":[["Motivo para compartir","________________________________________________________"]]},
  {"type":"table","rows":[["CTA","________________________________________________________"]]},
  {"type":"table","rows":[["Qué NO copiar","________________________________________________________"]]},
  {"type":"table","rows":[["Patrón abstracto reusable","________________________________________________________"]]},
  {"type":"kicker","text":"LECTURA DE DATOS"},
  {"type":"h1","text":"Qué mirar en Top Ads"},
  {"type":"bullet","text":"2s view rate: señal temprana de si la apertura consigue retener al menos un instante."},
  {"type":"bullet","text":"6s view rate: útil para comparar si la pieza sostiene interés más allá del hook."},
  {"type":"bullet","text":"CTR: indica si quienes vieron también hicieron clic; no explica por sí solo por qué."},
  {"type":"bullet","text":"CVR: conecta interacciones con la acción de conversión definida."},
  {"type":"bullet","text":"Gráfico segundo a segundo: buscá picos y caídas para formular hipótesis sobre escenas."},
  {"type":"callout","text":"No uses benchmarks universales\nDuración, categoría, objetivo, placement, audiencia y oferta cambian mucho. Compará creativos dentro de contextos equivalentes y usá tus propios históricos como línea base."},
  {"type":"kicker","text":"08  |  DIAGNOSTICO"},
  {"type":"h1","text":"Diagnóstico A.R.D.A.: cambiá una cosa por vez"},
  {"type":"p","text":"Cuando una pieza falla, el instinto es cambiar todo. Eso produce actividad, no aprendizaje. Diagnosticá desde el principio del embudo creativo."},
  {"type":"table","rows":[
    ["Síntoma","Etapa","Hipótesis","Qué testear"],
    ["No se detienen","ATENCIÓN","Probá otro primer cuadro, frase, contraste o resultado visible.","Hook / primer frame"],
    ["Se detienen y se van","RETENCIÓN","Acortá contexto, sumá progresión, demostración o bucle abierto.","Cuerpo / ritmo"],
    ["Miran pero no reaccionan","DESEO","Revisá relevancia, prueba, beneficio y motivo para compartir/guardar.","Ángulo / prueba"],
    ["Hacen clic pero no avanzan","ACCIÓN + OFERTA","Revisá coherencia anuncio-landing, fricción, precio y CTA.","Oferta / landing"],
    ["Compran poco aun con interés","ECONOMÍA","Puede no ser un problema creativo: margen, precio, confianza, checkout, mercado.","Negocio"]
  ]},
  {"type":"kicker","text":"UNA HIPOTESIS A LA VEZ"},
  {"type":"h1","text":"Árbol de decisiones creativo"},
  {"type":"table","rows":[["1","¿La persona se detiene?\nNO > test de hook visual/verbal.  SI > seguí."]]},
  {"type":"table","rows":[["2","¿Sigue mirando después de la apertura?\nNO > test de ritmo/progresión.  SI > seguí."]]},
  {"type":"table","rows":[["3","¿Hay señales de interés?\nNO > test de ángulo, beneficio, prueba.  SI > seguí."]]},
  {"type":"table","rows":[["4","¿Hace la acción pedida?\nNO > test de CTA/oferta/landing.  SI > escalá con cautela y seguí testeando."]]},
  {"type":"kicker","text":"09  |  SWIPE FILE"},
  {"type":"h1","text":"25 patrones creativos para no empezar de cero"},
  {"type":"p","text":"No son anuncios para copiar. Son puntos de partida que podés combinar con los hooks y estructuras anteriores."},
  {"type":"kicker","text":"SWIPE FILE"},
  {"type":"h1","text":"Producto físico"},
  {"type":"h2","text":"1. Demo imposible de ignorar"},
  {"type":"p","text":"Arrancá con la acción más visual del producto antes de decir su nombre."},
  {"type":"h2","text":"2. Comparación lado a lado"},
  {"type":"p","text":"Dos formas de resolver lo mismo; el producto gana por una diferencia visible."},
  {"type":"h2","text":"3. Problema cotidiano exagerado sólo visualmente"},
  {"type":"p","text":"Una escena reconocible, sin claims exagerados, seguida de la solución."},
  {"type":"h2","text":"4. Detalle satisfactorio"},
  {"type":"p","text":"Textura, sonido, encastre, apertura, limpieza, transformación."},
  {"type":"h2","text":"5. Objeción en pantalla"},
  {"type":"p","text":"“¿Pero dura?” / “¿entra?” / “¿sirve para…?” y prueba inmediata."},
  {"type":"kicker","text":"SWIPE FILE"},
  {"type":"h1","text":"Servicio"},
  {"type":"h2","text":"1. Auditoría de 15 segundos"},
  {"type":"p","text":"Mostrá un error realista y qué revisar primero."},
  {"type":"h2","text":"2. Lo que haría si..."},
  {"type":"p","text":"Escenario del cliente + 3 decisiones."},
  {"type":"h2","text":"3. Antes de contratar..."},
  {"type":"p","text":"Checklist que eleva criterio y autoridad."},
  {"type":"h2","text":"4. Microcaso"},
  {"type":"p","text":"Problema > ajuste > cambio verificable."},
  {"type":"h2","text":"5. Mito del rubro"},
  {"type":"p","text":"Una creencia común + contexto + criterio correcto."},
  {"type":"kicker","text":"SWIPE FILE"},
  {"type":"h1","text":"Negocio local"},
  {"type":"h2","text":"1. POV de llegada"},
  {"type":"p","text":"Entrada al lugar > producto > momento final."},
  {"type":"h2","text":"2. Producto estrella"},
  {"type":"p","text":"El más pedido y por qué."}
];
