import type { ReaderBlock } from "./types";

export const readerBlocks3: ReaderBlock[] = [
  {"type":"kicker","text":"HOOKS 091-100"},
  {"type":"h1","text":"Oferta / CTA anticipado"},
  {"type":"table","rows":[["091","Si querés [resultado], te muestro exactamente por dónde empezaría."]]},
  {"type":"table","rows":[["092","Para quien está cansado de [problema], esto puede simplificar bastante el proceso."]]},
  {"type":"table","rows":[["093","Armé [recurso] para que no tengas que inventar [tarea] desde cero."]]},
  {"type":"table","rows":[["094","Si vendés [categoría], acá tenés una estructura que podés usar hoy."]]},
  {"type":"table","rows":[["095","Esto es para vos si querés [deseo] pero no sabés [bloqueo]."]]},
  {"type":"table","rows":[["096","En vez de darte teoría, te dejo una plantilla para [resultado]."]]},
  {"type":"table","rows":[["097","Si hoy tuvieras que lanzar un anuncio, empezaría con esto."]]},
  {"type":"table","rows":[["098","Una sola idea, tres versiones de anuncio. Así las haría."]]},
  {"type":"table","rows":[["099","No hace falta complicarlo: [mecanismo simple] + [beneficio] + [acción]."]]},
  {"type":"table","rows":[["100","Si esto te ahorra una mala campaña, ya valió la pena."]]},
  {"type":"kicker","text":"04  |  ESTRUCTURAS"},
  {"type":"h1","text":"30 estructuras: el esqueleto antes del copy"},
  {"type":"p","text":"Una estructura no es un guion rígido. Es una secuencia de decisiones que evita que el video sea una colección de frases sin progresión."},
  {"type":"h2","text":"01. Interrupción > Dolor > Mecanismo > CTA"},
  {"type":"callout","text":"FÓRMULA\nRompé el patrón, nombrá el problema, explicá por qué tu solución funciona y cerrá con una acción."},
  {"type":"p","text":"Mejor para: Servicios y productos con un mecanismo fácil de explicar."},
  {"type":"h2","text":"02. Antes > Después > Puente"},
  {"type":"callout","text":"FÓRMULA\nMostrá la situación inicial, el resultado deseado y qué conecta ambos estados."},
  {"type":"p","text":"Mejor para: Transformaciones visibles, organización, estética, educación."},
  {"type":"h2","text":"03. Error > Consecuencia > Corrección"},
  {"type":"callout","text":"FÓRMULA\nMarcá un error común, hacé visible su costo y mostrale la corrección."},
  {"type":"p","text":"Mejor para: Profesionales, consultores, SaaS, formación."},
  {"type":"h2","text":"04. Mito > Giro > Evidencia > CTA"},
  {"type":"callout","text":"FÓRMULA\nEmpezá con una creencia popular, contradecila con contexto y mostrá una razón creíble."},
  {"type":"p","text":"Mejor para: Categorías saturadas de consejos repetidos."},
  {"type":"h2","text":"05. Demostración > Reacción > Beneficio"},
  {"type":"callout","text":"FÓRMULA\nMostrá el producto actuando antes de explicarlo; después traducí lo visto a un beneficio."},
  {"type":"p","text":"Mejor para: Productos físicos y negocios con resultado visual."},
  {"type":"h2","text":"06. Pregunta incómoda > Diagnóstico > Solución"},
  {"type":"callout","text":"FÓRMULA\nAbrí con una pregunta que expone un problema y convertí la respuesta en tu oferta."},
  {"type":"p","text":"Mejor para: Servicios B2B, marketing, salud no clínica, educación."},
  {"type":"h2","text":"07. Lista rápida > Prioridad > CTA"},
  {"type":"callout","text":"FÓRMULA\nEntregá 3-5 puntos, destacá el más importante y cerrá con un siguiente paso."},
  {"type":"p","text":"Mejor para: Contenido educativo y lead generation."},
  {"type":"h2","text":"08. Objeción > Prueba > Reencuadre"},
  {"type":"callout","text":"FÓRMULA\nUsá la objeción principal como hook y respondela con evidencia o demostración."},
  {"type":"p","text":"Mejor para: Ofertas donde precio, tiempo o confianza frenan."},
  {"type":"h2","text":"09. Historia mínima > Tensión > Descubrimiento"},
  {"type":"callout","text":"FÓRMULA\nContá una microhistoria con un problema, sostené la incertidumbre y revelá el aprendizaje."},
  {"type":"p","text":"Mejor para: Marcas personales y servicios."},
  {"type":"h2","text":"10. POV > Situación > Deseo"},
  {"type":"callout","text":"FÓRMULA\nEntrá directo en una escena que el cliente quiere vivir."},
  {"type":"p","text":"Mejor para: Lifestyle, gastronomía, turismo, moda, fitness."},
  {"type":"h2","text":"11. Comparación A/B > Diferencia > Elección"},
  {"type":"callout","text":"FÓRMULA\nMostrá dos formas de hacer lo mismo y explicá por qué una funciona mejor."},
  {"type":"p","text":"Mejor para: Educación, herramientas, diseño, servicios."},
  {"type":"h2","text":"12. Resultado primero > Cómo se hizo > CTA"},
  {"type":"callout","text":"FÓRMULA\nAbrí con el final atractivo y retrocedé para explicar el proceso."},
  {"type":"p","text":"Mejor para: Casos, tutoriales, producto visual."},
  {"type":"h2","text":"13. Dato sorprendente > Contexto > Aplicación"},
  {"type":"callout","text":"FÓRMULA\nUsá un dato relevante, contextualizalo y bajalo a una decisión útil."},
  {"type":"p","text":"Mejor para: B2B, educación, tecnología. Evitá estadísticas sin fuente."},
  {"type":"h2","text":"14. Señal > Significado > Acción"},
  {"type":"callout","text":"FÓRMULA\nMostrá una señal observable, explicá qué significa y qué hacer."},
  {"type":"p","text":"Mejor para: Diagnóstico, mantenimiento, servicios profesionales."},
  {"type":"h2","text":"15. Problema invisible > Revelación > Solución"},
  {"type":"callout","text":"FÓRMULA\nHacé visible algo que el cliente no estaba mirando."},
  {"type":"p","text":"Mejor para: Servicios donde el problema no es obvio."},
  {"type":"h2","text":"16. Unboxing > Detalle > Momento de uso"},
  {"type":"callout","text":"FÓRMULA\nAbrí, enfocá el detalle más deseable y mostrale dónde entra en la vida del cliente."},
  {"type":"p","text":"Mejor para: Productos físicos, regalos, belleza, tecnología."},
  {"type":"h2","text":"17. Tutorial express > Error > Atajo"},
  {"type":"callout","text":"FÓRMULA\nMostrá el proceso, señalá dónde se complica y ofrecé el atajo."},
  {"type":"p","text":"Mejor para: Educación y herramientas."},
  {"type":"h2","text":"18. Reacción real > Motivo > Oferta"},
  {"type":"callout","text":"FÓRMULA\nAbrí con una reacción, explicá qué la provoca y conectá con el producto."},
  {"type":"p","text":"Mejor para: Gastronomía, experiencias, estética, regalos."},
  {"type":"h2","text":"19. Reto > Proceso > Resultado"},
  {"type":"callout","text":"FÓRMULA\nDefiní un reto concreto, ejecutalo y mostrá el resultado."},
  {"type":"p","text":"Mejor para: Productos demostrables y contenido entretenido."},
  {"type":"h2","text":"20. Comentario > Respuesta > Demostración"},
  {"type":"callout","text":"FÓRMULA\nUsá una pregunta/comentario real como apertura y respondé con evidencia."},
  {"type":"p","text":"Mejor para: UGC, community-led, objeciones frecuentes."},
  {"type":"h2","text":"21. Deseo > Fricción > Eliminación"},
  {"type":"callout","text":"FÓRMULA\nNombrá lo que quiere la persona, el obstáculo que la frena y cómo lo reducís."},
  {"type":"p","text":"Mejor para: Servicios, apps, cursos, conveniencia."},
  {"type":"h2","text":"22. Pérdida > Causa > Prevención"},
  {"type":"callout","text":"FÓRMULA\nMostrá qué se pierde por no actuar y cómo evitarlo, sin miedo exagerado."},
  {"type":"p","text":"Mejor para: Mantenimiento, productividad, negocios."},
  {"type":"h2","text":"23. Microcaso > Cambio > Lección"},
  {"type":"callout","text":"FÓRMULA\nCaso breve, cambio concreto y aprendizaje transferible."},
  {"type":"p","text":"Mejor para: Profesionales y consultores."},
  {"type":"h2","text":"24. Producto en contexto > Problema > Encaje"},
  {"type":"callout","text":"FÓRMULA\nMostrá el producto en el momento exacto donde resuelve algo."},
  {"type":"p","text":"Mejor para: Hogar, cocina, indumentaria, accesorios."},
  {"type":"h2","text":"25. Teaser > Revelación progresiva > Oferta"},
  {"type":"callout","text":"FÓRMULA\nMostrá partes del resultado y dosificá la explicación."},
  {"type":"p","text":"Mejor para: Lanzamientos y novedades."},
  {"type":"h2","text":"26. Ranking > Criterio > Ganador situacional"},
  {"type":"callout","text":"FÓRMULA\nOrdená opciones según un criterio y explicá cuál conviene para cada caso."},
  {"type":"p","text":"Mejor para: Catálogos, variantes, servicios escalonados."},
  {"type":"h2","text":"27. Qué haría si... > 3 pasos > CTA"},
  {"type":"callout","text":"FÓRMULA\nPlanteá un escenario del cliente y resolvelo en tres pasos concretos."}
];
