import type { ReaderBlock } from "./types";

export const readerBlocks6: ReaderBlock[] = [
  {"type":"h2","text":"3. Detrás de escena"},
  {"type":"p","text":"Preparación real, manos, sonido, proceso."},
  {"type":"h2","text":"4. Plan para hoy"},
  {"type":"p","text":"“Si estás en [zona], guardate este plan”."},
  {"type":"h2","text":"5. Compartilo con..."},
  {"type":"p","text":"Una excusa concreta para mandar el video a alguien."},
  {"type":"kicker","text":"SWIPE FILE"},
  {"type":"h1","text":"Profesional"},
  {"type":"h2","text":"1. Explicación sin jerga"},
  {"type":"p","text":"Concepto complejo explicado con analogía simple."},
  {"type":"h2","text":"2. Señal a observar"},
  {"type":"p","text":"Qué puede indicar algo y cuándo consultar."},
  {"type":"h2","text":"3. Error frecuente"},
  {"type":"p","text":"Conducta común + por qué conviene revisar contexto."},
  {"type":"h2","text":"4. Pregunta de paciente/cliente"},
  {"type":"p","text":"Respuesta general, límites claros, CTA de consulta."},
  {"type":"h2","text":"5. Checklist de decisión"},
  {"type":"p","text":"Qué mirar antes de elegir, firmar, comprar o avanzar."},
  {"type":"kicker","text":"SWIPE FILE"},
  {"type":"h1","text":"Producto digital"},
  {"type":"h2","text":"1. Screen recording primero"},
  {"type":"p","text":"Resultado en pantalla desde el segundo 0."},
  {"type":"h2","text":"2. De blanco a listo"},
  {"type":"p","text":"Pantalla vacía > plantilla > resultado."},
  {"type":"h2","text":"3. Tour de 3 recursos"},
  {"type":"p","text":"Qué contiene y cuándo usar cada parte."},
  {"type":"h2","text":"4. Una plantilla, tres usos"},
  {"type":"p","text":"Mismo recurso aplicado a escenarios distintos."},
  {"type":"h2","text":"5. Problema de tiempo"},
  {"type":"p","text":"Mostrar cómo el recurso reduce decisiones, no prometer milagros."},
  {"type":"kicker","text":"10  |  CONTROL FINAL"},
  {"type":"h1","text":"Checklist de 25 puntos antes de publicar"},
  {"type":"table","rows":[["☐","01. ¿Se entiende el tema sin contexto en los primeros 2-3 segundos?"]]},
  {"type":"table","rows":[["☐","02. ¿El primer cuadro tiene movimiento, contraste, rostro, producto o tensión visual?"]]},
  {"type":"table","rows":[["☐","03. ¿El hook promete una razón concreta para seguir mirando?"]]},
  {"type":"table","rows":[["☐","04. ¿El anuncio evita presentaciones largas y logos antes del valor?"]]},
  {"type":"table","rows":[["☐","05. ¿Cada bloque agrega información nueva?"]]},
  {"type":"table","rows":[["☐","06. ¿Hay una pregunta, tensión o curiosidad abierta que empuje al siguiente segundo?"]]},
  {"type":"table","rows":[["☐","07. ¿El producto/servicio aparece lo suficientemente temprano?"]]},
  {"type":"table","rows":[["☐","08. ¿El beneficio está traducido a una escena o resultado entendible?"]]},
  {"type":"table","rows":[["☐","09. ¿Hay una sola idea principal?"]]},
  {"type":"table","rows":[["☐","10. ¿Sacaste frases corporativas y adjetivos vacíos?"]]},
  {"type":"table","rows":[["☐","11. ¿La prueba corresponde a la promesa?"]]},
  {"type":"table","rows":[["☐","12. ¿Evitás estadísticas o claims que no podés respaldar?"]]},
  {"type":"table","rows":[["☐","13. ¿Hay subtítulos/texto legible si se mira sin sonido?"]]},
  {"type":"table","rows":[["☐","14. ¿El texto en pantalla es breve y no tapa lo importante?"]]},
  {"type":"table","rows":[["☐","15. ¿El ritmo cambia antes de que la escena se vuelva predecible?"]]},
  {"type":"table","rows":[["☐","16. ¿Existe al menos un motivo para guardar o compartir?"]]},
  {"type":"table","rows":[["☐","17. ¿El CTA es una acción concreta y coherente con el nivel de intención?"]]},
  {"type":"table","rows":[["☐","18. ¿La landing/oferta dice lo mismo que el anuncio?"]]},
  {"type":"table","rows":[["☐","19. ¿El precio y condiciones son claros?"]]},
  {"type":"table","rows":[["☐","20. ¿La pieza funciona en vertical 9:16 para placements cortos?"]]},
  {"type":"table","rows":[["☐","21. ¿Grabaste una segunda versión sólo cambiando el hook?"]]},
  {"type":"table","rows":[["☐","22. ¿Tenés otra variante cambiando el visual inicial?"]]},
  {"type":"table","rows":[["☐","23. ¿Sabés qué métrica/observación vas a usar para decidir cuál seguir?"]]},
  {"type":"table","rows":[["☐","24. ¿Vas a testear una variable por vez?"]]},
  {"type":"table","rows":[["☐","25. ¿El anuncio sigue siendo honesto aunque quieras maximizar atención?"]]},
  {"type":"kicker","text":"DE IDEA A APRENDIZAJE"},
  {"type":"h1","text":"Sprint creativo de 7 días"},
  {"type":"table","rows":[["Día 1","Oferta y deseo","Elegí una oferta, un público y completá 10 ángulos."]]},
  {"type":"table","rows":[["Día 2","Hooks","Escribí 20 hooks; seleccioná 6 por tensión y claridad."]]},
  {"type":"table","rows":[["Día 3","Estructuras","Convertí 3 hooks en 3 estructuras distintas."]]},
  {"type":"table","rows":[["Día 4","Producción","Grabá/creá 6 variantes. Cambiá una variable por vez."]]},
  {"type":"table","rows":[["Día 5","Publicación / test","Lanzá con condiciones comparables y etiquetá cada variante."]]},
  {"type":"table","rows":[["Día 6","Diagnóstico","Anotá observaciones por Atención, Retención, Deseo, Acción."]]},
  {"type":"table","rows":[["Día 7","Iteración","Duplicá el mejor patrón y producí 3 nuevas variantes."]]},
  {"type":"callout","text":"Meta del sprint\nNo es encontrar una pieza perfecta en siete días. Es terminar la semana sabiendo más sobre qué ángulos, hooks y pruebas generan respuesta en TU mercado."},
  {"type":"kicker","text":"REGISTRO"},
  {"type":"h1","text":"Ficha simple de aprendizaje por creativo"},
  {"type":"table","rows":[
    ["Creativo","Ángulo","Hook","Qué retuvo","Qué falló","Próximo test"],
    ["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""],["","","","","",""]
  ]},
  {"type":"p","text":"Consejo: guardá capturas y links de cada versión. La memoria creativa sin registro se llena de sesgos."},
  {"type":"kicker","text":"REFERENCIAS"},
  {"type":"h1","text":"Fuentes y herramientas para seguir aprendiendo"},
  {"type":"p","text":"Este playbook combina principios propios de estrategia creativa con herramientas y recomendaciones oficiales de plataformas. Como las interfaces y recomendaciones cambian, revisá siempre la documentación vigente."},
  {"type":"h2","text":"TikTok for Business - Creative Best Practices"},
  {"type":"p","text":"Hook temprano, propuesta de valor, CTA, estética nativa, texto y variedad creativa."},
  {"type":"p","text":"ads.tiktok.com/resources/help/article/creative-best-practices"},
  {"type":"h2","text":"TikTok Creative Center"},
  {"type":"p","text":"Top Ads, tendencias, inspiración y herramientas creativas."},
  {"type":"p","text":"ads.tiktok.com/business/creativecenter"},
  {"type":"h2","text":"Meta Ad Library"},
  {"type":"p","text":"Anuncios activos en Facebook e Instagram para estudiar ofertas, formatos y ángulos."},
  {"type":"p","text":"facebook.com/ads/library"},
  {"type":"kicker","text":"CIERRE"},
  {"type":"h1","text":"La ventaja no está en tener una idea. Está en poder producir la siguiente."},
  {"type":"p","text":"Un anuncio con potencial viral no nace de perseguir una fórmula secreta. Nace de observar mejor, plantear una tensión concreta, mostrar valor rápido, sostener el interés y aprender de cada prueba."},
  {"type":"strong","text":"Usá este Playbook como sistema: IDEA → HOOK → RETENCIÓN → DESEO → ACCIÓN → DIAGNÓSTICO → NUEVA VARIANTE."},
  {"type":"callout","text":"Tu próxima tarea\nElegí un producto o servicio. Tomá 3 hooks de este Playbook, combiná cada uno con una estructura distinta y producí tres versiones hoy. No busques perfección: buscá información útil para la próxima iteración."}
];
