import type { ReaderBlock } from "./types";

export const readerBlocks4: ReaderBlock[] = [
  {"type":"p","text":"Mejor para: Educación, negocios, marketing."},
  {"type":"h2","text":"28. Costo oculto > Ejemplo > Solución"},
  {"type":"callout","text":"FÓRMULA\nConvertí un problema abstracto en tiempo, esfuerzo o oportunidad perdida."},
  {"type":"p","text":"Mejor para: B2B, productividad, servicios."},
  {"type":"h2","text":"29. Transformación visual > Texto mínimo > CTA"},
  {"type":"callout","text":"FÓRMULA\nDejá que el contraste visual cargue la historia y usá texto sólo para orientar."},
  {"type":"p","text":"Mejor para: Belleza, orden, diseño, restauración."},
  {"type":"h2","text":"30. Confesión > Cambio de enfoque > Invitación"},
  {"type":"callout","text":"FÓRMULA\nAdmití un error o cambio de opinión, explicá la nueva forma y llamá a probarla."},
  {"type":"p","text":"Mejor para: Marca personal y autoridad."},
  {"type":"kicker","text":"05  |  GUIONES"},
  {"type":"h1","text":"20 guiones: copiá la lógica, no la voz"},
  {"type":"p","text":"Reemplazá los corchetes, simplificá y leelo en voz alta. Si una frase no suena como algo que dirías, reescribila."},
  {"type":"h2","text":"01. 10s - Producto físico: demostración instantánea"},
  {"type":"callout","text":"VISUAL: el producto resolviendo el problema desde el cuadro 1.\nVOZ/TEXTO: “Si [problema] te pasa siempre, mirá esto. [Producto] hace [mecanismo visible] para que [beneficio].”\nCIERRE: “Mirá los detalles / conseguí el tuyo acá.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"02. 15s - Producto físico: antes y después"},
  {"type":"callout","text":"VISUAL: antes 2s > uso 7s > después 4s.\nVOZ: “Antes: [frustración]. Después de usar [producto]: [resultado]. Lo importante no es [característica], es que [beneficio emocional/práctico].”\nCTA: “Si querés [resultado], tenés el link acá.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"03. 20s - Producto físico: objeción precio"},
  {"type":"callout","text":"HOOK: “Sí, hay opciones más baratas. La diferencia está acá.”\nCUERPO: mostrás 2-3 detalles que explican duración, comodidad o resultado.\nCIERRE: “Si para vos importa [criterio], esta es la versión que elegiría.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"04. 30s - Producto físico: UGC reseña honesta"},
  {"type":"callout","text":"HOOK: “Lo compré por [motivo] y pensé que iba a ser uno más.”\nCUERPO: “Lo primero que noté fue [detalle]. Después [microresultado]. Lo que no me esperaba fue [sorpresa realista].”\nCTA: “Si [perfil] te describe, fijate si todavía está disponible.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"05. 10s - Servicio: dolor directo"},
  {"type":"callout","text":"HOOK: “Si [problema] te cuesta [consecuencia], no empieces por [solución típica].”\nCUERPO: “Primero corregí [causa]. Eso es exactamente lo que trabajamos en [servicio].”\nCTA: “Escribinos ‘INFO’.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"06. 15s - Servicio: tres señales"},
  {"type":"callout","text":"HOOK: “3 señales de que necesitás revisar [área].”\nCUERPO: “Uno: [señal]. Dos: [señal]. Tres: [señal].”\nCIERRE: “Si te pasan dos o más, mandame [palabra] y te digo por dónde empezaría.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"07. 20s - Servicio: mini caso"},
  {"type":"callout","text":"HOOK: “[Cliente tipo] tenía [problema]. No le faltaba [suposición], le faltaba [causa].”\nCUERPO: “Cambiamos [acción 1] y [acción 2]. El resultado fue [cambio verificable, sin exagerar].”\nCTA: “Si estás en una situación parecida, escribime.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"08. 30s - Servicio: autoridad sin presumir"},
  {"type":"callout","text":"HOOK: “Después de trabajar con [tipo de casos], hay un patrón que se repite.”\nCUERPO: “La mayoría intenta [error]. Pero antes conviene [principio]. Porque [explicación simple].”\nCIERRE: “Si querés que revisemos tu caso, tenés el enlace.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"09. 10s - Negocio local: deseo visual"},
  {"type":"callout","text":"VISUAL: primer plano irresistible del producto/experiencia.\nTEXTO: “POV: pasaste por [zona] y encontraste esto.”\nCIERRE: ubicación + “guardalo para el finde”."},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"10. 15s - Negocio local: recomendación"},
  {"type":"callout","text":"HOOK: “Si estás en [ciudad/barrio] y te gusta [deseo], guardate este lugar.”\nCUERPO: 3 planos: ambiente, producto, detalle diferencial.\nCTA: “Mandáselo a la persona con la que vendrías.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"11. 20s - Negocio local: detrás de escena"},
  {"type":"callout","text":"HOOK: “Esto pasa antes de que llegue a tu mesa.”\nCUERPO: proceso real, manos, sonidos, preparación.\nTEXTO: “Hecho [diferencial real].”\nCTA: “Estamos en [zona].”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"12. 30s - Negocio local: historia del producto estrella"},
  {"type":"callout","text":"HOOK: “Este es el producto que más nos piden y hay una razón.”\nCUERPO: mostrás preparación + por qué existe + detalle diferencial.\nCTA: “Si todavía no lo probaste, guardá este video.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"13. 10s - Profesional: mito"},
  {"type":"callout","text":"HOOK: “No, [mito común] no siempre significa [conclusión].”\nCUERPO: “Lo que hay que mirar es [criterio].”\nCTA: “Guardalo y consultá a un profesional para tu caso.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"14. 15s - Profesional: error frecuente"},
  {"type":"callout","text":"HOOK: “El error que veo todo el tiempo en [tema].”\nCUERPO: “Hacer [error] sin revisar [dato/contexto].”\nCTA: “Si querés, te dejo una lista de qué revisar.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"15. 20s - Profesional: explicación simple"},
  {"type":"callout","text":"HOOK: “Te explico [concepto] sin palabras raras.”\nCUERPO: analogía cotidiana + ejemplo.\nCIERRE: “Ahora, si tu situación tiene [variable], cambia; por eso cada caso se evalúa aparte.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"16. 30s - Profesional: checklist"},
  {"type":"callout","text":"HOOK: “Antes de [decisión], revisá estas cuatro cosas.”\nCUERPO: cuatro puntos con texto grande y ejemplo breve.\nCTA: “Guardá el video. Si necesitás una evaluación personalizada, podés consultar.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"17. 10s - Producto digital: resultado"},
  {"type":"callout","text":"HOOK: “De [caos inicial] a [resultado concreto] usando una sola plantilla.”\nCUERPO: screen recording rápido.\nCTA: “La plantilla está en el link.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"18. 15s - Producto digital: pantalla en blanco"},
  {"type":"callout","text":"HOOK: “Si abrís [herramienta] y no sabés por dónde empezar, copiá esto.”\nCUERPO: mostrás estructura.\nCTA: “En [producto] tenés [cantidad] variantes.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"19. 20s - Producto digital: objeción de tiempo"},
  {"type":"callout","text":"HOOK: “No necesitás ver 8 horas de curso para resolver [microproblema].”\nCUERPO: “Abrís [recurso], elegís [ruta], completás [pasos].”\nCTA: “Está pensado para usar mientras hacés.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"h2","text":"20. 30s - Producto digital: valor apilado"},
  {"type":"callout","text":"HOOK: “Si hoy tuviera que empezar [tarea] desde cero, no improvisaría.”\nCUERPO: mostrás 3-4 recursos del kit y para qué sirve cada uno.\nCIERRE: “La idea no es tener más información; es tener qué usar cuando la necesitás.”"},
  {"type":"p","text":"TIP: grabá una segunda versión cambiando sólo el primer cuadro o frase."},
  {"type":"kicker","text":"06  |  IA"},
  {"type":"h1","text":"20 prompts para usar IA como director creativo"},
  {"type":"p","text":"Pegá contexto real. Cuanto más específica sea tu oferta, público, deseo, objeciones y evidencia, menos genérica será la salida."},
  {"type":"callout","text":"Regla\nNo le pidas a la IA “haceme un anuncio viral”. Pedile una tarea creativa concreta y dale un criterio para evaluar la respuesta."},
  {"type":"h2","text":"01. Generador de 20 ángulos"},
  {"type":"callout","text":"Actuá como director creativo de performance. Vendo [PRODUCTO] a [PUBLICO]. Su deseo principal es [DESEO] y su frustración es [PROBLEMA]. Generá 20 ángulos de anuncio distintos. Para cada uno: tensión inicial, promesa razonable, mecanismo y visual de apertura. Evitá clichés y promesas no verificables."},
  {"type":"h2","text":"02. Hooks por nivel de conciencia"},
  {"type":"callout","text":"Para [OFERTA], generá 5 hooks para público que no conoce el problema, 5 para quien conoce el problema, 5 para quien conoce soluciones y 5 para quien ya compara proveedores. Que cada hook sea grabable en menos de 3 segundos."},
  {"type":"h2","text":"03. Hook visual"},
  {"type":"callout","text":"Dame 15 ideas de hooks VISUALES sin depender de una frase hablada para vender [PRODUCTO]. Cada idea debe poder entenderse con sonido apagado y mostrar tensión, contraste, movimiento o resultado."},
  {"type":"h2","text":"04. Retención segundo a segundo"},
  {"type":"callout","text":"Tomá este guion: [PEGAR GUION]. Marcá dónde puede caer la atención. Reescribilo en bloques de 0-3s, 3-7s, 7-12s y 12-20s. En cada bloque agregá una razón nueva para seguir mirando."},
  {"type":"h2","text":"05. 10 variantes de una idea"},
  {"type":"callout","text":"Idea base: [IDEA]. Creá 10 variantes cambiando sólo una variable por vez: hook, visual inicial, objeción, prueba, tono o CTA. Conservá el mismo producto y oferta."},
  {"type":"h2","text":"06. Convertir característica en deseo"},
  {"type":"callout","text":"Producto: [PRODUCTO]. Características: [LISTA]. Para cada característica, traducila a beneficio funcional, beneficio emocional y escena concreta donde el cliente lo siente."},
  {"type":"h2","text":"07. Objeciones como anuncios"},
  {"type":"callout","text":"Listá las 15 objeciones más probables antes de comprar [OFERTA]. Convertí cada objeción en un hook + respuesta + tipo de prueba que debería mostrar."},
  {"type":"h2","text":"08. Guiones UGC naturales"},
  {"type":"callout","text":"Creá 5 guiones UGC de 20 segundos para [PRODUCTO]. Deben sonar como una persona real, no como una marca. Incluir: comentario inicial espontáneo, detalle específico, mini demostración y CTA suave."},
  {"type":"h2","text":"09. Ideas de shareability"},
  {"type":"callout","text":"Para [TEMA/OFERTA], generá 20 ideas que alguien tendría motivos para compartir con otra persona. Clasificalas por utilidad, identificación, sorpresa, humor liviano y recomendación."}
];
