/* eslint-disable @next/next/no-img-element */
"use client";

import { useState,type CSSProperties,type PointerEvent as ReactPointerEvent } from "react";
import { flushSync } from "react-dom";
import type { Experience,SceneType } from "./data";
import ScratchReveal from "./ScratchReveal";
import CandleBlow from "./CandleBlow";
import LightReveal from "./LightReveal";
import HoldReveal from "./HoldReveal";
import { getExperienceCopy,type DeepPartial,type ExperienceCopy } from "./experienceCopy";
import { mediaBelongsToScene } from "./mediaRouting";

export type ThiPhoto={url:string;caption?:string;fit?:"cover"|"contain";position?:"center"|"top"|"bottom"|"left"|"right";scene?:SceneType};
export type ThiAudio={url:string;caption?:string;scene?:SceneType};
export type ThiVideo={url:string;caption?:string;scene?:SceneType};

function AttachedSceneMedia({scene,photos,audios,videos}:{scene:SceneType;photos:ThiPhoto[];audios:ThiAudio[];videos:ThiVideo[]}){
  const attachedPhotos=scene==="memories"?[]:photos;
  const attachedAudios=scene==="voices"?[]:audios;
  const attachedVideos=scene==="video"?[]:videos;
  if(!attachedPhotos.length&&!attachedAudios.length&&!attachedVideos.length) return null;
  return <aside className="thi-attached-media" data-attached-scene={scene}>
    {attachedPhotos.slice(0,2).map((item,index)=><figure className={`thi-attached-photo p${index+1}`} key={item.url}>
      <img src={item.url} alt={item.caption||"Recuerdo"} style={{objectFit:item.fit||"cover",objectPosition:item.position||"center"}}/>
      {item.caption&&<figcaption>{item.caption}</figcaption>}
    </figure>)}
    {attachedVideos.slice(0,1).map(item=><figure className="thi-attached-video" key={item.url}>
      <video src={item.url} controls playsInline preload="metadata"/>
      {item.caption&&<figcaption>{item.caption}</figcaption>}
    </figure>)}
    {attachedAudios.slice(0,2).map((item,index)=><article className="thi-attached-audio" key={item.url}>
      <span>♪</span><div><small>{item.caption||`Audio ${index+1}`}</small><audio src={item.url} controls preload="metadata"/></div>
    </article>)}
  </aside>;
}

export default function ExperienceEngine({experience,letterText,photoMedia,audioMedia,videoMedia,copyOverride,initialScene}:{experience:Experience;letterText?:string;photoMedia?:ThiPhoto[];audioMedia?:ThiAudio[];videoMedia?:ThiVideo[];copyOverride?:DeepPartial<ExperienceCopy>;initialScene?:SceneType}){
  const initialSceneIndex=initialScene?Math.max(0,experience.recipe.indexOf(initialScene)):0;
  const [sceneIndex,setSceneIndex]=useState(initialSceneIndex);const [runId,setRunId]=useState(0);const [transitioning,setTransitioning]=useState(false);const [direction,setDirection]=useState<"forward"|"back">("forward");
  const [stars,setStars]=useState<number[]>([]);const [letterOpen,setLetterOpen]=useState(false);const [scratched,setScratched]=useState(false);const [candlesOut,setCandlesOut]=useState(false);const [popped,setPopped]=useState<number[]>([]);
  const [quizChoice,setQuizChoice]=useState<number|null>(null);const [vaultOpen,setVaultOpen]=useState(false);const [capsuleOpen,setCapsuleOpen]=useState(false);const [voicesPlayed,setVoicesPlayed]=useState<number[]>([]);
  const [doorOpen,setDoorOpen]=useState(false);const [lightRevealed,setLightRevealed]=useState(false);const [holdRevealed,setHoldRevealed]=useState(false);const [lastStar,setLastStar]=useState<number|null>(null);

  const copy=getExperienceCopy(experience,copyOverride);const scenes=experience.recipe;const current=scenes[sceneIndex];const total=scenes.length;const progress=((sceneIndex+1)/total)*100;
  const token=(value:string)=>value.replaceAll("{giver}",experience.demoGiver).replaceAll("{recipient}",experience.demoRecipient).replaceAll("{opening}",experience.opening).replaceAll("{closing}",experience.closing);
  const countText=(one:string,many:string,count:number)=>token((count===1?one:many).replace("{count}",String(count)));
  const titleLines=(parts:string[])=>parts.map((line,index)=><span key={`${line}-${index}`}>{token(line)}{index<parts.length-1&&<br/>}</span>);
  const memoryLines=copy.memories.items.length?copy.memories.items:["Ese día todavía no sabíamos todo lo que iba a venir.","Los mejores recuerdos casi nunca avisan que van a ser importantes.","Sin darnos cuenta, empezamos a coleccionar un mundo propio."];
  const starLines=copy.stars.items.length?copy.stars.items:["Tu forma de hacer hogar.","Cómo te reís cuando te olvidás de cuidarte.","La calma que traés sin darte cuenta.","Todo lo que todavía soñamos.","Que te volvería a elegir."];
  const balloonLines=copy.balloons.items.length?copy.balloons.items:["Te queremos","Tu risa","Hoy mandás vos","Una salida","Un abrazo","Nunca cambies"];
  const timelineEntries=copy.timeline.entries.length?copy.timeline.entries:[{title:"El comienzo",body:"Cuando todavía no sabíamos en qué se iba a convertir todo esto."},{title:"Ese día",body:"Uno de esos momentos que después entendemos que fueron gigantes."},{title:"Hoy",body:"La historia sigue. Y eso es lo mejor."}];
  const voiceEntries=copy.voices.entries.length?copy.voices.entries:[{name:experience.demoGiver,message:"Esto es sólo una pequeña forma de decirte cuánto importás."}];
  const currentPhotos=(photoMedia||[]).filter(item=>mediaBelongsToScene("image",item.scene,current));
  const currentAudios=(audioMedia||[]).filter(item=>mediaBelongsToScene("audio",item.scene,current));
  const currentVideos=(videoMedia||[]).filter(item=>mediaBelongsToScene("video",item.scene,current));
  const demoPhotos=(experience.demo.photos||[]).map((item,index)=>({url:item.url,caption:memoryLines[index]||undefined,fit:"cover" as const,position:item.position||"center" as const}));
  const displayPhotos=current==="memories"?(currentPhotos.length?currentPhotos.slice(0,8):demoPhotos):[];
  const hasAttachedMedia=(current!=="memories"&&currentPhotos.length>0)||(current!=="voices"&&currentAudios.length>0)||(current!=="video"&&currentVideos.length>0);

  const resetAllInteractions=()=>{setStars([]);setLastStar(null);setLetterOpen(false);setScratched(false);setCandlesOut(false);setPopped([]);setQuizChoice(null);setVaultOpen(false);setCapsuleOpen(false);setVoicesPlayed([]);setDoorOpen(false);setLightRevealed(false);setHoldRevealed(false)};
  const resetSceneState=(type:SceneType)=>{if(type==="stars"){setStars([]);setLastStar(null)};if(type==="letter")setLetterOpen(false);if(type==="scratch")setScratched(false);if(type==="candles")setCandlesOut(false);if(type==="balloons")setPopped([]);if(type==="quiz")setQuizChoice(null);if(type==="vault")setVaultOpen(false);if(type==="capsule")setCapsuleOpen(false);if(type==="voices")setVoicesPlayed([]);if(type==="door")setDoorOpen(false);if(type==="light")setLightRevealed(false);if(type==="hold")setHoldRevealed(false)};
  const haptic=(pattern:number|number[]=10)=>{if(typeof navigator!=="undefined"&&"vibrate" in navigator)navigator.vibrate(pattern)};
  const restart=()=>{resetAllInteractions();setDirection("back");setTransitioning(false);setSceneIndex(0);setRunId(v=>v+1);haptic([8,22,8])};

  const playDemoVoice=(message:string)=>{try{if(typeof window==="undefined"||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(message);utterance.lang="es-AR";utterance.rate=.92;utterance.pitch=.9;const voices=window.speechSynthesis.getVoices();const preferred=voices.find(v=>v.lang.toLowerCase().startsWith("es-ar"))||voices.find(v=>v.lang.toLowerCase().startsWith("es"));if(preferred)utterance.voice=preferred;window.speechSynthesis.speak(utterance)}catch{}};
  const playFx=(kind:"chime"|"pop"|"door"|"seal"|"unlock")=>{try{const context=new AudioContext();const oscillator=context.createOscillator();const gain=context.createGain();const now=context.currentTime;oscillator.connect(gain);gain.connect(context.destination);const presets={chime:{type:"sine" as OscillatorType,start:760,end:1180,duration:.34,volume:.035},pop:{type:"triangle" as OscillatorType,start:240,end:72,duration:.12,volume:.05},door:{type:"sine" as OscillatorType,start:95,end:48,duration:.42,volume:.035},seal:{type:"triangle" as OscillatorType,start:330,end:180,duration:.18,volume:.035},unlock:{type:"sine" as OscillatorType,start:420,end:820,duration:.42,volume:.035}};const preset=presets[kind];oscillator.type=preset.type;oscillator.frequency.setValueAtTime(preset.start,now);oscillator.frequency.exponentialRampToValueAtTime(Math.max(1,preset.end),now+preset.duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(preset.volume,now+.02);gain.gain.exponentialRampToValueAtTime(.0001,now+preset.duration);oscillator.start(now);oscillator.stop(now+preset.duration+.02);window.setTimeout(()=>void context.close(),Math.ceil((preset.duration+.1)*1000))}catch{}};

  const moveTo=(nextIndex:number,dir:"forward"|"back")=>{if(nextIndex<0||nextIndex>=total||nextIndex===sceneIndex)return;const destination=scenes[nextIndex];const commitScene=()=>{resetSceneState(destination);setDirection(dir);setTransitioning(false);setSceneIndex(nextIndex);setRunId(v=>v+1)};haptic(8);if(typeof document!=="undefined"&&typeof window!=="undefined"){const viewDocument=document as Document&{startViewTransition?:(update:()=>void)=>unknown};const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;if(viewDocument.startViewTransition&&!reduced){viewDocument.startViewTransition(()=>flushSync(commitScene));return}}commitScene()};
  const next=()=>moveTo(Math.min(total-1,sceneIndex+1),"forward");const prev=()=>moveTo(Math.max(0,sceneIndex-1),"back");
  const openDoor=()=>{if(doorOpen)return;setDoorOpen(true);haptic([12,35,9]);playFx("door")};

  const canAdvance=()=>{switch(current){case"intro":case"memories":case"timeline":case"video":return true;case"door":return doorOpen;case"light":return lightRevealed;case"hold":return holdRevealed;case"stars":return stars.length>=3;case"scratch":return scratched;case"letter":return letterOpen;case"candles":return candlesOut;case"balloons":return popped.length>=3;case"voices":return voicesPlayed.length>0;case"quiz":return quizChoice!==null;case"vault":return vaultOpen;case"capsule":return capsuleOpen;default:return false}};

  function scene(type:SceneType){
    switch(type){
      case"intro":return <section className="thi-scene thi-intro thi-scene-rich"><div className="thi-glow a"/><div className="thi-glow b"/><div className="thi-intro-constellation" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div><p className="thi-kicker">{token(copy.intro.kicker)}</p><h1>{token(copy.intro.title)}</h1><div className="thi-hairline"/><p className="thi-lead">{token(copy.intro.lead)}</p><button data-action="advance" className="thi-primary thi-primary-premium" onClick={next}><span>{token(copy.intro.cta)}</span><b>→</b></button><small>{token(copy.intro.footnote)}</small></section>;
      case"door":return <section className="thi-scene thi-scene-door thi-scene-rich"><p className="thi-kicker">{token(copy.door.kicker)}</p><h2>{titleLines(copy.door.title)}</h2><div className="thi-door-light" aria-hidden="true"/><div className="thi-door-floor" aria-hidden="true"/><button data-action="open-door" className={`thi-door-wrap ${doorOpen?"opening":""}`} onClick={openDoor}><span className="thi-door-frame"><span className="thi-door"><i/><b/></span><span className="thi-door-world"/></span></button>{!doorOpen?<p className="thi-hint">{token(copy.door.closedHint)}</p>:<button data-action="advance" className="thi-primary thi-door-enter" onClick={next}>{token(copy.door.openCta)}</button>}</section>;
      case"memories":return <section className="thi-scene thi-scene-memories thi-scene-rich"><p className="thi-kicker">{token(copy.memories.kicker)}</p><h2>{titleLines(copy.memories.title)}</h2><div className="thi-film">{(displayPhotos.length?displayPhotos:memoryLines.map(caption=>({url:"",caption,fit:"cover" as const,position:"center" as const}))).map((item,i)=><article className={`thi-memory m${(i%3)+1}`} key={item.url||item.caption||i}><div className="thi-memory-photo">{item.url&&<img src={item.url} alt="" loading="eager" decoding="async" referrerPolicy="no-referrer" style={{objectFit:item.fit||"cover",objectPosition:item.position||"center"}}/>}<span>{String(i+1).padStart(2,"0")}</span><i className="thi-photo-sheen"/></div><p>{token(item.caption||memoryLines[i%memoryLines.length])}</p></article>)}</div><button data-action="advance" className="thi-primary" onClick={next}>{token(copy.memories.cta)}</button></section>;
      case"light":return <section className="thi-scene thi-scene-light thi-scene-rich"><p className="thi-kicker">{token(copy.light.kicker)}</p><h2>{token(copy.light.title)}</h2><LightReveal accent={experience.accent} kicker={token(copy.light.kicker)} title={token(copy.light.title)} secret={token(copy.light.secret)} hint={token(copy.light.hint)} revealedLabel={token(copy.light.revealedLabel)} ariaLabel={token(copy.light.ariaLabel)} revealed={lightRevealed} onReveal={()=>{setLightRevealed(true);haptic([7,20,10]);playFx("chime")}}/>{lightRevealed&&<button data-action="advance" className="thi-primary" onClick={next}>{token(copy.light.cta)}</button>}</section>;
      case"stars":return <section className="thi-scene thi-scene-stars thi-scene-rich"><div className="thi-sky-dust" aria-hidden="true"/><p className="thi-kicker">{token(copy.stars.kicker)}</p><h2>{titleLines(copy.stars.title)}</h2>{experience.slug==="pareja"?<div className={`thi-stars-cinematic ${stars.length>=3?"complete":""}`}>
        <svg viewBox="0 0 760 390" aria-hidden="true"><path d="M92 104 C214 56 292 92 380 191 C476 292 555 275 672 104"/></svg>
        {starLines.map((line,i)=><button data-action="star" aria-label={stars.includes(i)?token(line):`${token(copy.stars.hiddenLabel)} ${i+1}`} key={line} className={`thi-star-point s${i+1} ${stars.includes(i)?"revealed":""} ${lastStar===i?"current":""}`} onClick={()=>{setStars(v=>v.includes(i)?v:[...v,i]);setLastStar(i);haptic(9);playFx("chime")}}><span>✦</span><i/></button>)}
        <div className={`thi-star-story ${lastStar!==null?"visible":""}`}>
          <small>{lastStar===null?"tocá una luz":`${String((lastStar||0)+1).padStart(2,"0")} / ${String(starLines.length).padStart(2,"0")}`}</small>
          <blockquote>{lastStar===null?"Hay cosas que nunca entraron en una foto.":token(starLines[lastStar])}</blockquote>
        </div>
        <div className="thi-star-count"><span>{stars.length}</span><i/> <small>{stars.length===1?"descubierta":"descubiertas"}</small></div>
      </div>:<div className={`thi-stars ${stars.length>=3?"complete":""}`}><svg className="thi-constellation-lines" viewBox="0 0 700 350" aria-hidden="true"><path d="M105 66 L585 50 L350 175 L130 305 L570 300 L350 175 Z"/></svg>{starLines.map((line,i)=><button data-action="star" key={line} className={stars.includes(i)?"revealed":""} onClick={()=>{setStars(v=>v.includes(i)?v:[...v,i]);haptic(9);playFx("chime")}}><span>✦</span><em>{stars.includes(i)?token(line):token(copy.stars.hiddenLabel)}</em><i/></button>)}{stars.length>=3&&<div className="thi-constellation-complete"><span>✦</span><small>{token(copy.stars.completeLabel)}</small></div>}</div>}<button data-action="advance" className="thi-primary" disabled={stars.length<3} onClick={next}>{stars.length<3?countText(copy.stars.remainingOne,copy.stars.remainingMany,3-stars.length):token(copy.stars.cta)}</button></section>;
      case"scratch":return <section className="thi-scene thi-scene-scratch thi-scene-rich"><p className="thi-kicker">{token(copy.scratch.kicker)}</p><h2>{titleLines(copy.scratch.title)}</h2><ScratchReveal accent={experience.accent} eyebrow={token(copy.scratch.eyebrow)} reward={token(copy.scratch.reward)} note={token(copy.scratch.note)} coverTitle={token(copy.scratch.coverTitle)} coverHint={token(copy.scratch.coverHint)} fallbackLabel={token(copy.scratch.fallbackLabel)} revealed={scratched} onReveal={()=>{setScratched(true);haptic([8,20,8]);playFx("chime")}}/><button data-action="advance" className="thi-primary" disabled={!scratched} onClick={next}>{token(copy.scratch.cta)}</button></section>;
      case"hold":return <section className="thi-scene thi-scene-hold thi-scene-rich"><p className="thi-kicker">{token(copy.hold.kicker)}</p><h2>{titleLines(copy.hold.title)}</h2><HoldReveal accent={experience.accent} symbol={token(copy.hold.symbol)} prompt={token(copy.hold.prompt)} reveal={token(copy.hold.reveal)} instruction={token(copy.hold.instruction)} revealed={holdRevealed} onReveal={()=>{setHoldRevealed(true);haptic([18,45,18,45,28]);playFx("seal")}}/>{holdRevealed&&<button data-action="advance" className="thi-primary" onClick={next}>{token(copy.hold.cta)}</button>}</section>;
      case"letter":return <section className="thi-scene thi-scene-letter thi-scene-rich"><p className="thi-kicker">{token(copy.letter.kicker)}</p><h2>{titleLines(copy.letter.title)}</h2><div className="thi-letter-aura" aria-hidden="true"/><button data-action="open-letter" className={`thi-envelope ${letterOpen?"open":""}`} onClick={()=>{setLetterOpen(true);haptic([10,30,8]);playFx("seal")}}><span className="back"/><span className="paper"><small>{token(copy.letter.recipientLabel)}</small><strong>{copyOverride?.letter?.body?token(String(copyOverride.letter.body)):letterText||token(copy.letter.body)}</strong><em>{token(copy.letter.signature)}</em></span><span className="front"/><span className="wax">♥</span></button>{!letterOpen?<p className="thi-hint">{token(copy.letter.sealHint)}</p>:<button data-action="advance" className="thi-primary" onClick={next}>{token(copy.letter.cta)}</button>}</section>;
      case"candles":return <section className="thi-scene thi-scene-candles thi-scene-rich"><p className="thi-kicker">{token(copy.candles.kicker)}</p><h2>{titleLines(copy.candles.title)}</h2><div className={`thi-cake ${candlesOut?"out":""}`}><div className="thi-cake-shadow"/><div className="thi-cake-plate"/><div className="thi-cake-body"><span className="thi-cake-top"/><span className="thi-cake-icing"/><span className="thi-cake-sprinkles"/></div><div className="thi-candles">{[0,1,2,3,4].map(i=><span key={i}><i/><b/></span>)}</div></div><CandleBlow blown={candlesOut} labels={{idle:token(copy.candles.micIdle),active:token(copy.candles.micActive),fallback:token(copy.candles.tapFallback),unavailable:token(copy.candles.tapUnavailable)}} onBlow={()=>{setCandlesOut(true);haptic([10,20,10]);playFx("chime")}}/>{candlesOut&&<><p className="thi-wish-made">{token(copy.candles.wishLabel)}</p><button data-action="advance" className="thi-ghost" onClick={next}>{token(copy.candles.cta)}</button></>}</section>;
      case"balloons":return <section className="thi-scene thi-scene-balloons thi-scene-rich"><p className="thi-kicker">{token(copy.balloons.kicker)}</p><h2>{titleLines(copy.balloons.title)}</h2><div className="thi-balloons">{balloonLines.map((line,i)=><button data-action="balloon" key={line} className={popped.includes(i)?"pop":""} onClick={()=>{setPopped(v=>v.includes(i)?v:[...v,i]);haptic(10);playFx("pop")}}><span>{popped.includes(i)?token(line):""}</span><i>{popped.includes(i)?"✦":token(copy.balloons.popLabel)}</i></button>)}</div><button data-action="advance" className="thi-primary" disabled={popped.length<3} onClick={next}>{popped.length<3?countText(copy.balloons.remainingOne,copy.balloons.remainingMany,3-popped.length):token(copy.balloons.cta)}</button></section>;
      case"timeline":return <section className="thi-scene thi-scene-timeline thi-scene-rich"><p className="thi-kicker">{token(copy.timeline.kicker)}</p><h2>{titleLines(copy.timeline.title)}</h2><div className="thi-timeline"><div className="thi-timeline-line" aria-hidden="true"/>{timelineEntries.map((entry,index)=><article key={entry.title}><span>{String(index+1).padStart(2,"0")}</span><i/><strong>{token(entry.title)}</strong><p>{token(entry.body)}</p></article>)}</div><button data-action="advance" className="thi-primary" onClick={next}>{token(copy.timeline.cta)}</button></section>;
      case"voices":return <section className="thi-scene thi-scene-voices thi-scene-rich"><p className="thi-kicker">{token(copy.voices.kicker)}</p><h2>{titleLines(copy.voices.title)}</h2>{currentAudios.length?<div className="thi-voices">{currentAudios.map((a,i)=><article key={a.url} className={voicesPlayed.includes(i)?"thi-voice-audio played":"thi-voice-audio"}><span>♪</span><strong>{a.caption||`Mensaje ${i+1}`}</strong><audio data-action="real-audio" src={a.url} controls preload="metadata" onPlay={()=>{setVoicesPlayed(v=>v.includes(i)?v:[...v,i]);haptic(6)}}/></article>)}</div>:experience.slug==="pareja"?<div className="thi-romantic-audio">{voiceEntries.slice(0,1).map((voice,i)=><button data-action="demo-voice" key={voice.name} className={voicesPlayed.includes(i)?"played":""} onClick={()=>{setVoicesPlayed(v=>v.includes(i)?v:[...v,i]);haptic([7,18,7]);playDemoVoice(token(voice.message))}} aria-label={token(copy.voices.playLabel)}><span className="thi-audio-avatar">{voice.name.slice(0,1)}</span><span className="thi-audio-copy"><small>{token(copy.voices.noteLabel.replace("{name}",voice.name))}</small><strong>{voicesPlayed.includes(i)?token(copy.voices.playingLabel):token(copy.voices.playLabel)}</strong><i className="thi-waveform" aria-hidden="true">{Array.from({length:24}).map((_,bar)=><b key={bar}/>)}</i></span><span className="thi-audio-play">{voicesPlayed.includes(i)?"❚❚":"▶"}</span></button>)}{voicesPlayed.length>0&&<p>“{token(voiceEntries[0].message)}”</p>}</div>:<div className="thi-voices">{voiceEntries.map((voice,i)=><button data-action="demo-voice" key={voice.name} className={voicesPlayed.includes(i)?"played":""} onClick={()=>{setVoicesPlayed(v=>v.includes(i)?v:[...v,i]);haptic(6)}}><span>{voicesPlayed.includes(i)?"▶":"●"}</span><strong>{token(voice.name)}</strong><small>{voicesPlayed.includes(i)?`“${token(voice.message)}”`:token(copy.voices.playLabel)}</small></button>)}</div>}<button data-action="advance" className="thi-primary" disabled={!voicesPlayed.length} onClick={next}>{token(copy.voices.cta)}</button></section>;
      case"quiz":return <section className="thi-scene thi-scene-quiz thi-scene-rich"><p className="thi-kicker">{token(copy.quiz.kicker)}</p><h2>{token(copy.quiz.question)}</h2><div className="thi-quiz">{copy.quiz.answers.map((answer,i)=><button data-action="quiz-answer" key={answer} className={quizChoice!==null&&i===copy.quiz.correctIndex?"ok":quizChoice===i?"wrong":""} onClick={()=>{setQuizChoice(i);haptic(8)}}><span>{String.fromCharCode(65+i)}</span>{token(answer)}<i>{quizChoice!==null&&i===copy.quiz.correctIndex?"✓":quizChoice===i?"·":""}</i></button>)}</div>{quizChoice!==null&&<p className="thi-lead thi-reveal-copy">{token(copy.quiz.after)}</p>}<button data-action="advance" className="thi-primary" disabled={quizChoice===null} onClick={next}>{token(copy.quiz.cta)}</button></section>;
      case"vault":return <section className="thi-scene thi-scene-vault thi-scene-rich"><p className="thi-kicker">{token(copy.vault.kicker)}</p><h2>{titleLines(copy.vault.title)}</h2><div className="thi-vault-aura" aria-hidden="true"/><button data-action="open-vault" className={`thi-vault ${vaultOpen?"open":""}`} onClick={()=>{setVaultOpen(true);haptic([12,40,12]);playFx("unlock")}}><span><i>◇</i><b/></span><strong>{token(vaultOpen?copy.vault.openLabel:copy.vault.closedLabel)}</strong><small>{token(vaultOpen?copy.vault.openSmall:copy.vault.closedSmall)}</small></button>{vaultOpen&&<><p className="thi-lead thi-reveal-copy">{token(copy.vault.reveal)}</p><button data-action="advance" className="thi-primary" onClick={next}>{token(copy.vault.cta)}</button></>}</section>;
      case"capsule":return <section className="thi-scene thi-scene-capsule thi-scene-rich"><p className="thi-kicker">{token(copy.capsule.kicker)}</p><h2>{titleLines(copy.capsule.title)}</h2><button data-action="open-capsule" className={`thi-capsule ${capsuleOpen?"open":""}`} onClick={()=>{setCapsuleOpen(true);haptic([8,25,8])}}><span>{token(copy.capsule.year)}<i/></span><strong>{token(capsuleOpen?copy.capsule.openLabel:copy.capsule.closedLabel)}</strong><p>{token(capsuleOpen?copy.capsule.open:copy.capsule.closed)}</p></button>{capsuleOpen&&<button data-action="advance" className="thi-primary" onClick={next}>{token(copy.capsule.cta)}</button>}</section>;
      case"video":return <section className="thi-scene thi-scene-video thi-scene-rich"><p className="thi-kicker">{token(copy.video.kicker)}</p><h2>{titleLines(copy.video.title)}</h2>{currentVideos.length?<div className="thi-video-wrap"><div className="thi-video-frame"><video src={currentVideos[0].url} controls playsInline preload="metadata"/></div>{currentVideos[0].caption&&<p>{currentVideos[0].caption}</p>}</div>:<div className="thi-video-placeholder"><span>▶</span><small>{token(copy.video.placeholder)}</small></div>}<button data-action="advance" className="thi-primary" onClick={next}>{token(copy.video.cta)}</button></section>;
      case"proposal":return <section className="thi-scene thi-final thi-proposal thi-scene-rich"><div className="thi-proposal-rings" aria-hidden="true"><i/><i/><i/></div><p className="thi-kicker">{token(copy.proposal.kicker)}</p><span className="thi-ring">◇</span><h2>{token(copy.proposal.title)}</h2><p className="thi-lead">{token(copy.proposal.lead)}</p><div className="thi-reactions">{copy.proposal.reactions.map(x=><button key={x} onClick={()=>haptic([10,20,10])}>{token(x)}</button>)}</div><small>{token(copy.proposal.createdWith)}</small></section>;
      case"finale":default:return <section className="thi-scene thi-final thi-scene-rich"><div className="thi-final-sparks" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div><p className="thi-kicker">{token(copy.finale.kicker)}</p><h2>{token(copy.finale.title)}</h2><p className="thi-lead">{token(copy.finale.lead)}</p><div className="thi-reactions">{copy.finale.reactions.map(x=><button key={x} onClick={()=>haptic(7)}>{token(x)}</button>)}</div><button data-action="restart" className="thi-ghost" onClick={restart}>{token(copy.finale.restartLabel)}</button><small>{token(copy.finale.createdWith)}</small></section>;
    }
  }

  const moveAtmosphere=(event:ReactPointerEvent<HTMLElement>)=>{const node=event.currentTarget;const width=Math.max(window.innerWidth,1);const height=Math.max(window.innerHeight,1);node.style.setProperty("--pointer-left",`${event.clientX}px`);node.style.setProperty("--pointer-top",`${event.clientY}px`);node.style.setProperty("--parallax-x",`${((event.clientX/width)-.5)*18}px`);node.style.setProperty("--parallax-y",`${((event.clientY/height)-.5)*14}px`)};

  return <main className={`thi-experience thi-experience-premium thi-theme-${experience.slug}`} style={{"--accent":experience.accent} as CSSProperties} data-experience={experience.slug} data-scene={current} onPointerMove={moveAtmosphere}>
    <div className="thi-pointer-light" aria-hidden="true"/><div className="thi-experience-noise" aria-hidden="true"/><div className="thi-experience-vignette" aria-hidden="true"/><div className="thi-experience-orb orb-a" aria-hidden="true"/><div className="thi-experience-orb orb-b" aria-hidden="true"/><div className="thi-theme-signature" aria-hidden="true"><i/><i/><i/></div>
    <div className="thi-scene-meta"><span>{token(copy.ui.sceneLabels[current])}</span><i/><small>{String(sceneIndex+1).padStart(2,"0")} / {String(total).padStart(2,"0")}</small></div>
    <button data-action="restart" className="thi-reset-journey" type="button" onClick={restart} aria-label={token(copy.ui.resetAria)}><span>↻</span><small>{token(copy.ui.resetLabel)}</small></button>
    <div className={`thi-scene-stage ${transitioning?"leaving":""} ${direction} ${hasAttachedMedia?"has-attached-media":""}`} key={`${runId}-${sceneIndex}-${current}`}>
      {scene(current)}
      <AttachedSceneMedia scene={current} photos={currentPhotos} audios={currentAudios} videos={currentVideos}/>
    </div>
    <div className="thi-progress thi-progress-premium"><button data-action="previous" onClick={prev} disabled={!sceneIndex||transitioning} aria-label={token(copy.ui.previousAria)}>←</button><div><span style={{width:`${progress}%`}}/></div><small>{Math.round(progress)}%</small><button data-action="next" className="thi-progress-next" onClick={next} disabled={!canAdvance()||sceneIndex>=total-1} aria-label={token(copy.ui.nextAria)}>→</button></div>
  </main>;
}
