import type { Merchant } from "@/domain/types";

export const merchants: Merchant[] = [
  {
    id: "merchant_moka",
    slug: "moka",
    name: "Moka",
    whatsappNumber: "5491100000000",
    rewardValidityDays: 7,
    theme: {
      displayName: "Moka",
      shortName: "Moka",
      monogram: "M",
      category: "coffee",
      businessType: "Café de especialidad",
      shareMode: "whatsapp_only",
      heroEyebrow: "Un ritual hecho para vos",
      heroTitle: "Hay algo especial esperando",
      heroCopy: "Descubrí el detalle que Moka preparó para tu próxima pausa.",
      mysteryLabel: "Sorpresa Moka",
      shareTitle: "Compartí tu pase para abrirlo",
      shareCopy: "Elegí dónde compartir tu pase. La sorpresa que te toca sigue siendo sólo tuya.",
      referralCopy: "Moka me dejó un pase sorpresa. Hay otro esperando por vos.",
      socialHeadline: "Moka dejó una sorpresa esperando",
      socialSubcopy: "Abrí tu propio pase y descubrí qué te toca.",
      palette: {
        canvas: "#E9DED0",
        canvasAccent: "#B6774C",
        surface: "#F8F2E9",
        surfaceRaised: "#FFFDF9",
        text: "#201712",
        textMuted: "#715D50",
        primary: "#8F4327",
        primaryHover: "#71321D",
        onPrimary: "#FFFDF9",
        accent: "#C07A4D",
        accentSecondary: "#6F8370",
        border: "#D9C7B2",
        success: "#356B50",
        warning: "#98611F",
        danger: "#A13B36",
        wheel: ["#8F4327", "#6F8370", "#C98552", "#563A2F", "#DDBE91"],
      },
    },
    prizes: [
      { id: "upgrade", name: "Upgrade de café", probability: 35 },
      { id: "medialuna", name: "Medialuna gratis en tu próxima visita", probability: 30 },
      { id: "discount_10", name: "10% en tu próxima visita", probability: 20 },
      { id: "free_coffee", name: "Café gratis", probability: 14 },
      { id: "special", name: "Premio especial Moka", probability: 1 },
    ],
  },
  {
    id: "merchant_atlas",
    slug: "atlas-barber",
    name: "Atlas Barber",
    whatsappNumber: "5491100000001",
    rewardValidityDays: 10,
    theme: {
      displayName: "Atlas Barber",
      shortName: "Atlas",
      monogram: "A",
      category: "barber",
      businessType: "Barbería contemporánea",
      shareMode: "whatsapp_only",
      heroEyebrow: "Tu próximo corte empieza acá",
      heroTitle: "Tu estilo tiene una sorpresa",
      heroCopy: "Abrí tu pase privado y descubrí un beneficio para tu próxima visita.",
      mysteryLabel: "Pase Atlas",
      shareTitle: "Pasá el código. Abrí tu beneficio.",
      shareCopy: "Elegí dónde compartir tu pase para que alguien de tu círculo encuentre el suyo.",
      referralCopy: "Atlas me dio un pase privado. Hay otro esperando por vos.",
      socialHeadline: "Hay un pase privado de Atlas para vos",
      socialSubcopy: "Entrá, abrilo y descubrí tu beneficio.",
      palette: {
        canvas: "#090E13",
        canvasAccent: "#273443",
        surface: "#101821",
        surfaceRaised: "#18232F",
        text: "#F3EFE6",
        textMuted: "#AAB5BF",
        primary: "#D0A34A",
        primaryHover: "#E1B967",
        onPrimary: "#17130B",
        accent: "#7C9EB2",
        accentSecondary: "#B87355",
        border: "#344250",
        success: "#76B692",
        warning: "#D2A64C",
        danger: "#E17B71",
        wheel: ["#D0A34A", "#334C60", "#A9664C", "#718B9B", "#7A6740"],
      },
    },
    prizes: [
      { id: "beard_detail", name: "Perfilado de barba sin cargo", probability: 30 },
      { id: "discount_15", name: "15% en tu próximo corte", probability: 30 },
      { id: "hair_treatment", name: "Tratamiento capilar premium", probability: 20 },
      { id: "product", name: "Producto de styling de regalo", probability: 15 },
      { id: "atlas_ritual", name: "Ritual Atlas completo", probability: 5 },
    ],
  },
  {
    id: "merchant_el_gordo_leo",
    slug: "el-gordo-leo",
    name: "Mini Mercado El Gordo Leo",
    whatsappNumber: "5492236818230",
    rewardValidityDays: 7,
    theme: {
      displayName: "Mini Mercado El Gordo Leo",
      shortName: "El Gordo Leo",
      monogram: "GL",
      category: "generic",
      businessType: "Mini mercado",
      shareMode: "whatsapp_only",
      stylePreset: "bold",
      fontPreset: "geometric",
      tone: "Premios para volver",
      heroEyebrow: "Hay algo para vos",
      heroTitle: "Tenemos un regalo para vos.",
      heroCopy: "El Gordo Leo preparó beneficios para clientes. Abrí tu pase, compartilo y descubrí qué te toca.",
      mysteryLabel: "Pase El Gordo Leo",
      shareTitle: "Antes de descubrir el tuyo, regalale uno a alguien.",
      shareCopy: "Compartilo por WhatsApp. La otra persona también recibe su propio regalo y el tuyo sigue siendo solo tuyo.",
      referralCopy: "El Gordo Leo está regalando premios para la próxima compra 🎁 Probá tu pase.",
      socialHeadline: "Hay un regalo esperando en El Gordo Leo",
      socialSubcopy: "Abrí tu pase y descubrí qué te toca para tu próxima compra.",
      palette: {
        canvas: "#F2EAD5",
        canvasAccent: "#F6C945",
        surface: "#FFF7DF",
        surfaceRaised: "#FFFDF6",
        text: "#17382D",
        textMuted: "#426056",
        primary: "#E95C35",
        primaryHover: "#CE4928",
        onPrimary: "#FFFFFF",
        accent: "#F6C945",
        accentSecondary: "#2D7759",
        border: "#E7D9B8",
        success: "#2D7759",
        warning: "#C78312",
        danger: "#B83A31",
        wheel: ["#E95C35", "#2D7759", "#F6C945", "#D98A2B", "#244D40"],
      },
    },
    prizes: [
      { id: "discount_5", name: "5% de descuento en tu próxima compra", probability: 35 },
      { id: "discount_10", name: "10% de descuento en tu próxima compra", probability: 25 },
      { id: "discount_15", name: "15% de descuento en tu próxima compra", probability: 10 },
      { id: "cassata", name: "Helado cassata de regalo en tu próxima compra", probability: 15 },
      { id: "bombon", name: "Bombón escocés de regalo en tu próxima compra", probability: 15 },
    ],
  },
  {
    id: "merchant_volga",
    slug: "volga",
    name: "Volga",
    whatsappNumber: "5493544568000",
    rewardValidityDays: 30,
    theme: {
      displayName: "Volga",
      shortName: "Volga",
      monogram: "V",
      category: "generic",
      businessType: "Almacén",
      shareMode: "whatsapp_only",
      stylePreset: "luxury",
      fontPreset: "editorial",
      tone: "Almacén",
      logoDataUrl: "/brands/volga.svg",
      heroEyebrow: "Un detalle para vos",
      heroTitle: "Tenemos un regalo para vos.",
      heroCopy: "Volga preparó un beneficio para tu próxima compra. Descubrilo en menos de un minuto.",
      mysteryLabel: "Regalo Volga",
      shareTitle: "Antes de descubrir el tuyo, regalale uno a alguien.",
      shareCopy: "Compartilo por WhatsApp. La otra persona también recibe su propio regalo y el tuyo sigue siendo solo tuyo.",
      referralCopy: "Te mandé un regalo de Volga 🎁 Abrí el tuyo y descubrí qué te toca.",
      socialHeadline: "Hay un regalo de Volga esperando por vos",
      socialSubcopy: "Abrilo y descubrí tu beneficio para una próxima compra.",
      palette: {
        canvas: "#050607",
        canvasAccent: "#F4A300",
        surface: "#0B0E10",
        surfaceRaised: "#12171B",
        text: "#F3F7F9",
        textMuted: "#9AA8B2",
        primary: "#F4A300",
        primaryHover: "#FFB81C",
        onPrimary: "#0A0A0A",
        accent: "#E4321A",
        accentSecondary: "#9CC2D8",
        border: "#303A41",
        success: "#5AA56F",
        warning: "#F4A300",
        danger: "#D93624",
        wheel: ["#DDE8EE", "#E4321A", "#F4A300"],
      },
    },
    prizes: [
      { id: "nuts_20", name: "20% OFF en mix de frutos secos", probability: 34 },
      { id: "deli_10", name: "10% OFF en fiambres y quesos", probability: 33 },
      { id: "beer_10", name: "10% OFF en cervezas", probability: 33 },
    ],
  },
  {
    id: "merchant_saimond",
    slug: "saimond",
    name: "Saimond",
    whatsappNumber: "5492645845990",
    rewardValidityDays: 30,
    theme: {
      displayName: "Saimond",
      shortName: "Saimond",
      monogram: "S",
      category: "generic",
      businessType: "Petshop",
      shareMode: "whatsapp_only",
      stylePreset: "bold",
      fontPreset: "humanist",
      tone: "Todo para tu mascota",
      logoDataUrl: "/brands/saimond-original.jpg",
      heroEyebrow: "Peluquería canina",
      heroTitle: "Tenemos un regalo para vos.",
      heroCopy: "Saimond preparó un beneficio para tu próxima compra. Descubrilo en menos de un minuto.",
      mysteryLabel: "Regalo Saimond",
      shareTitle: "Antes de descubrir el tuyo, regalale uno a alguien.",
      shareCopy: "Compartilo por WhatsApp. La otra persona también recibe su propio regalo y el tuyo sigue siendo solo tuyo.",
      referralCopy: "Te mandé un regalo de Saimond 🎁 Abrí el tuyo y descubrí tu beneficio.",
      socialHeadline: "Hay un regalo de Saimond esperando por vos",
      socialSubcopy: "Abrilo y descubrí tu beneficio para tu próxima compra.",
      palette: {
        canvas: "#DDF4FF",
        canvasAccent: "#63C5EE",
        surface: "#F7FCFF",
        surfaceRaised: "#FFFFFF",
        text: "#0B2A54",
        textMuted: "#486580",
        primary: "#8C0028",
        primaryHover: "#71001F",
        onPrimary: "#FFFFFF",
        accent: "#FFD20A",
        accentSecondary: "#1188E8",
        border: "#A8DCF2",
        success: "#2F9A54",
        warning: "#D9A500",
        danger: "#A6002D",
        wheel: ["#8C0028", "#FFD20A", "#63C5EE", "#0B2A54"],
      },
    },
    prizes: [
      { id: "discount_10", name: "10% de descuento en tu próxima compra", probability: 100 },
    ],
  },
  {
    id: "merchant_carnes_roma",
    slug: "carnes-roma",
    name: "Carnes Roma",
    whatsappNumber: "5493804478760",
    rewardValidityDays: 30,
    theme: {
      displayName: "Carnes Roma",
      shortName: "Roma",
      monogram: "R",
      category: "generic",
      businessType: "Carnicería",
      shareMode: "whatsapp_only",
      stylePreset: "bold",
      fontPreset: "editorial",
      tone: "Carnicería",
      heroEyebrow: "Un regalo para vos",
      heroTitle: "Tenemos un regalo para vos.",
      heroCopy: "Carnes Roma preparó un beneficio para tu próxima compra. Descubrilo en menos de un minuto.",
      mysteryLabel: "Regalo Carnes Roma",
      shareTitle: "Antes de descubrir el tuyo, regalale uno a alguien.",
      shareCopy: "Compartilo por WhatsApp. La otra persona también recibe su propio regalo y el tuyo sigue siendo solo tuyo.",
      referralCopy: "Te mandé un regalo de Carnes Roma 🎁 Abrí el tuyo y descubrí tu beneficio.",
      socialHeadline: "Hay un regalo de Carnes Roma esperando por vos",
      socialSubcopy: "Abrilo y descubrí tu beneficio para tu próxima compra.",
      palette: {
        canvas: "#070707",
        canvasAccent: "#F06A12",
        surface: "#111111",
        surfaceRaised: "#181818",
        text: "#F7F3EE",
        textMuted: "#BCAFA3",
        primary: "#F06A12",
        primaryHover: "#FF7C24",
        onPrimary: "#120A05",
        accent: "#FF7A1A",
        accentSecondary: "#F1F1F1",
        border: "#33261D",
        success: "#4FA36A",
        warning: "#F6A43A",
        danger: "#D94C1A",
        wheel: ["#F06A12", "#111111", "#F1F1F1"],
      },
    },
    prizes: [
      { id: "discount_10", name: "10% de descuento en tu próxima compra", probability: 100 },
    ],
  },
  {
    id: "merchant_centro_estetica_lindy",
    slug: "centro-estetica-lindy",
    name: "Centro Estética Lindy",
    whatsappNumber: "5493813874434",
    rewardValidityDays: 30,
    theme: {
      displayName: "Centro Estética Lindy",
      shortName: "Lindy",
      monogram: "L",
      category: "generic",
      businessType: "Estética",
      shareMode: "whatsapp_only",
      stylePreset: "luxury",
      fontPreset: "editorial",
      tone: "Bienestar y belleza",
      logoDataUrl: "/brands/centro-estetica-lindy-v3.webp",
      heroEyebrow: "Un mimo para vos",
      heroTitle: "Tenemos un regalo para vos.",
      heroCopy: "Centro Estética Lindy preparó un beneficio especial para tu próxima visita. Descubrilo en menos de un minuto.",
      mysteryLabel: "Regalo Lindy",
      shareTitle: "Antes de descubrir el tuyo, regalale uno a alguien.",
      shareCopy: "Compartilo por WhatsApp. La otra persona también recibe su propio regalo y el tuyo sigue siendo solo tuyo.",
      referralCopy: "Te mandé un regalo de Centro Estética Lindy 🎁 Abrí el tuyo y descubrí tu beneficio.",
      socialHeadline: "Hay un regalo de Centro Estética Lindy esperando por vos",
      socialSubcopy: "Abrilo y descubrí tu beneficio para tu próxima visita.",
      palette: {
        canvas: "#F7F0F2",
        canvasAccent: "#E9D6DC",
        surface: "#FFFDFC",
        surfaceRaised: "#FFFFFF",
        text: "#4D313A",
        textMuted: "#8A6B75",
        primary: "#B76E79",
        primaryHover: "#A75D69",
        onPrimary: "#FFFFFF",
        accent: "#E5C1CA",
        accentSecondary: "#F2E4E8",
        border: "#E8D6DB",
        success: "#6F9E85",
        warning: "#D6A36F",
        danger: "#B95F6D",
        wheel: ["#B76E79", "#E5C1CA", "#F7F0F2", "#8F5F6A"],
      },
    },
    prizes: [
      { id: "discount_15", name: "15% de descuento en la próxima sesión", probability: 50 },
      { id: "feet_massage_2x1", name: "2 x 1 en masajes de pies", probability: 50 },
    ],
  },
  {
    id: "merchant_despensa_elvira",
    slug: "despensa-elvira",
    name: "Despensa Elvira",
    whatsappNumber: "5491138199795",
    rewardValidityDays: 30,
    theme: {
      displayName: "Despensa Elvira",
      shortName: "Elvira",
      monogram: "E",
      category: "generic",
      businessType: "Almacén / Despensa",
      shareMode: "whatsapp_only",
      stylePreset: "luxury",
      fontPreset: "editorial",
      tone: "Almacén de barrio",
      heroEyebrow: "Un detalle para vos",
      heroTitle: "Tenemos un regalo para vos.",
      heroCopy: "En Despensa Elvira preparamos un beneficio especial para tu próxima compra. Descubrilo en menos de un minuto.",
      mysteryLabel: "Regalo Elvira",
      shareTitle: "Antes de descubrir el tuyo, regalale uno a alguien.",
      shareCopy: "Compartilo por WhatsApp. La otra persona también recibe su propio regalo y el tuyo sigue siendo solo tuyo.",
      referralCopy: "Te mandé un regalo de Despensa Elvira 🎁 Abrilo y descubrí tu beneficio.",
      socialHeadline: "Hay un regalo de Despensa Elvira esperando por vos",
      socialSubcopy: "Abrilo y descubrí tu beneficio para tu próxima compra.",
      palette: {
        canvas: "#F5F0E5",
        canvasAccent: "#E6DDC7",
        surface: "#FFFDF8",
        surfaceRaised: "#FFFFFF",
        text: "#314238",
        textMuted: "#73796F",
        primary: "#4F6A52",
        primaryHover: "#425A45",
        onPrimary: "#FFFFFF",
        accent: "#B96E47",
        accentSecondary: "#EFE4D2",
        border: "#DED4C2",
        success: "#668D62",
        warning: "#C9934E",
        danger: "#B45E49",
        wheel: ["#4F6A52", "#B96E47", "#E6DDC7", "#9BAC91"],
      },
    },
    prizes: [
      { id: "discount_10", name: "10% de descuento en la próxima compra", probability: 100 },
    ],
  },
  {
    id: "merchant_los_chiquis",
    slug: "los-chiquis",
    name: "Los chiquis",
    whatsappNumber: "5491131568065",
    rewardValidityDays: 30,
    theme: {
      displayName: "Los chiquis",
      shortName: "Los chiquis",
      monogram: "LC",
      category: "generic",
      businessType: "Peluquería Canina",
      shareMode: "whatsapp_only",
      stylePreset: "luxury",
      fontPreset: "humanist",
      tone: "Cuidado y mimo para tu mascota",
      heroEyebrow: "Peluquería canina",
      heroTitle: "Tenemos un regalo para vos.",
      heroCopy: "Los chiquis es una peluquería canina y preparamos un beneficio especial para la próxima sesión de tu mascota. Descubrilo en menos de un minuto.",
      mysteryLabel: "Regalo Los chiquis",
      shareTitle: "Antes de descubrir el tuyo, regalale uno a alguien.",
      shareCopy: "Compartilo por WhatsApp. La otra persona también recibe su propio regalo y el tuyo sigue siendo solo tuyo.",
      referralCopy: "Te mandé un regalo de Los chiquis 🐾🎁 Abrilo y descubrí tu beneficio.",
      socialHeadline: "Hay un regalo de Los chiquis esperando por vos",
      socialSubcopy: "Peluquería canina Los chiquis: abrilo y descubrí tu beneficio para la próxima sesión de tu mascota.",
      palette: {
        canvas: "#F5F4EF",
        canvasAccent: "#D8E7DF",
        surface: "#FFFDF8",
        surfaceRaised: "#FFFFFF",
        text: "#29433F",
        textMuted: "#70817C",
        primary: "#5E8C82",
        primaryHover: "#4D766D",
        onPrimary: "#FFFFFF",
        accent: "#E59A72",
        accentSecondary: "#F2DFC9",
        border: "#D7E1DC",
        success: "#5E8C6A",
        warning: "#D79A53",
        danger: "#C66D64",
        wheel: ["#5E8C82", "#E59A72", "#F2DFC9", "#9FBEB5"],
      },
    },
    prizes: [
      { id: "discount_10", name: "10% de descuento en tu próxima sesión", probability: 100 },
    ],
  },
  {
    id: "merchant_fusion_de_sabores",
    slug: "fusion-de-sabores",
    name: "Fusión de sabores",
    whatsappNumber: "5493437520637",
    rewardValidityDays: 7,
    theme: {
      displayName: "Fusión de sabores",
      shortName: "Fusión",
      monogram: "FS",
      category: "generic",
      businessType: "Heladería y panadería",
      shareMode: "whatsapp_only",
      stylePreset: "luxury",
      fontPreset: "editorial",
      tone: "Dulce, artesanal y cercano",
      heroEyebrow: "Heladería & panadería",
      heroTitle: "Tenemos un regalo para vos.",
      heroCopy: "En Fusión de sabores preparamos un beneficio especial para tu próxima compra. Descubrilo en menos de un minuto.",
      mysteryLabel: "Regalo Fusión",
      shareTitle: "Antes de descubrir el tuyo, regalale uno a alguien.",
      shareCopy: "Compartilo por WhatsApp. La otra persona también recibe su propio regalo y el tuyo sigue siendo solo tuyo.",
      referralCopy: "Te mandé un regalo de Fusión de sabores 🍦🥐🎁 Abrilo y descubrí tu beneficio.",
      socialHeadline: "Hay un regalo de Fusión de sabores esperando por vos",
      socialSubcopy: "Heladería y panadería: abrilo y descubrí tu beneficio para tu próxima compra.",
      palette: {
        canvas: "#FBF4E8",
        canvasAccent: "#E7E7D1",
        surface: "#FFFDF8",
        surfaceRaised: "#FFFFFF",
        text: "#4B3A30",
        textMuted: "#7B7169",
        primary: "#8DAA79",
        primaryHover: "#769263",
        onPrimary: "#FFFFFF",
        accent: "#E98972",
        accentSecondary: "#F2D6A8",
        border: "#E6D9C7",
        success: "#71996D",
        warning: "#D7A451",
        danger: "#C96F63",
        wheel: ["#8DAA79", "#E98972", "#F2D6A8", "#8C6754"],
      },
    },
    prizes: [
      { id: "discount_10", name: "10% de descuento en tu próxima compra", probability: 100 },
    ],
  },
  {
    id: "merchant_roxy_comidas",
    slug: "roxy-comidas",
    name: "Roxy Comidas",
    whatsappNumber: "5493625203421",
    rewardValidityDays: 14,
    theme: {
      displayName: "Roxy Comidas",
      shortName: "Roxy",
      monogram: "RC",
      category: "generic",
      businessType: "Rotisería",
      shareMode: "whatsapp_only",
      stylePreset: "luxury",
      fontPreset: "humanist",
      tone: "Casero, rico y cercano",
      heroEyebrow: "Rotisería",
      heroTitle: "Tenemos un regalo para vos.",
      heroCopy: "En Roxy Comidas preparamos un beneficio especial para tu próxima compra. Descubrilo en menos de un minuto.",
      mysteryLabel: "Regalo Roxy",
      shareTitle: "Antes de descubrir el tuyo, regalale uno a alguien.",
      shareCopy: "Compartilo por WhatsApp. La otra persona también recibe su propio regalo y el tuyo sigue siendo solo tuyo.",
      referralCopy: "Te mandé un regalo de Roxy Comidas 🍽️🎁 Abrilo y descubrí tu beneficio.",
      socialHeadline: "Hay un regalo de Roxy Comidas esperando por vos",
      socialSubcopy: "Rotisería Roxy Comidas: abrilo y descubrí tu beneficio para tu próxima compra.",
      palette: {
        canvas: "#FAF2E8",
        canvasAccent: "#EAD8C3",
        surface: "#FFFDF9",
        surfaceRaised: "#FFFFFF",
        text: "#46362F",
        textMuted: "#7E7169",
        primary: "#A94F3D",
        primaryHover: "#8F4133",
        onPrimary: "#FFFFFF",
        accent: "#D98B4C",
        accentSecondary: "#F2D5A9",
        border: "#E6D3C1",
        success: "#6E9168",
        warning: "#D79A53",
        danger: "#B9584B",
        wheel: ["#A94F3D", "#D98B4C", "#F2D5A9", "#7D5A48"],
      },
    },
    prizes: [
      { id: "discount_10", name: "10% de descuento en tu próxima compra", probability: 100 },
    ],
  }
];

export function getMerchantBySlug(slug: string): Merchant | undefined {
  return merchants.find((merchant) => merchant.slug === slug);
}

export function getMerchantById(id: string): Merchant | undefined {
  return merchants.find((merchant) => merchant.id === id);
}
