import type { Merchant } from "@/domain/types";

export const merchants: Merchant[] = [
  {
    id: "merchant_moka",
    slug: "moka",
    name: "Moka",
    whatsappNumber: "5491100000000",
    rewardValidityDays: 7,
    theme: {
      displayName: "Moka",
      shortName: "Moka",
      monogram: "M",
      category: "coffee",
      heroEyebrow: "Un ritual hecho para vos",
      heroTitle: "Hay algo especial esperando",
      heroCopy: "Descubrí el detalle que Moka preparó para tu próxima pausa.",
      mysteryLabel: "Sorpresa Moka",
      shareTitle: "Compartí tu pase para abrirlo",
      shareCopy: "Elegí dónde compartir tu pase. La sorpresa que te toca sigue siendo sólo tuya.",
      referralCopy: "Moka me dejó un pase sorpresa. Hay otro esperando por vos.",
      socialHeadline: "Moka dejó una sorpresa esperando",
      socialSubcopy: "Abrí tu propio pase y descubrí qué te toca.",
      palette: {
        canvas: "#E9DED0",
        canvasAccent: "#B6774C",
        surface: "#F8F2E9",
        surfaceRaised: "#FFFDF9",
        text: "#201712",
        textMuted: "#715D50",
        primary: "#8F4327",
        primaryHover: "#71321D",
        onPrimary: "#FFFDF9",
        accent: "#C07A4D",
        accentSecondary: "#6F8370",
        border: "#D9C7B2",
        success: "#356B50",
        warning: "#98611F",
        danger: "#A13B36",
        wheel: ["#8F4327", "#6F8370", "#C98552", "#563A2F", "#DDBE91"],
      },
    },
    prizes: [
      { id: "upgrade", name: "Upgrade de café", probability: 35 },
      { id: "medialuna", name: "Medialuna gratis en tu próxima visita", probability: 30 },
      { id: "discount_10", name: "10% en tu próxima visita", probability: 20 },
      { id: "free_coffee", name: "Café gratis", probability: 14 },
      { id: "special", name: "Premio especial Moka", probability: 1 },
    ],
  },
  {
    id: "merchant_atlas",
    slug: "atlas-barber",
    name: "Atlas Barber",
    whatsappNumber: "5491100000001",
    rewardValidityDays: 10,
    theme: {
      displayName: "Atlas Barber",
      shortName: "Atlas",
      monogram: "A",
      category: "barber",
      heroEyebrow: "Tu próximo corte empieza acá",
      heroTitle: "Tu estilo tiene una sorpresa",
      heroCopy: "Abrí tu pase privado y descubrí un beneficio para tu próxima visita.",
      mysteryLabel: "Pase Atlas",
      shareTitle: "Pasá el código. Abrí tu beneficio.",
      shareCopy: "Elegí dónde compartir tu pase para que alguien de tu círculo encuentre el suyo.",
      referralCopy: "Atlas me dio un pase privado. Hay otro esperando por vos.",
      socialHeadline: "Hay un pase privado de Atlas para vos",
      socialSubcopy: "Entrá, abrilo y descubrí tu beneficio.",
      palette: {
        canvas: "#090E13",
        canvasAccent: "#273443",
        surface: "#101821",
        surfaceRaised: "#18232F",
        text: "#F3EFE6",
        textMuted: "#AAB5BF",
        primary: "#D0A34A",
        primaryHover: "#E1B967",
        onPrimary: "#17130B",
        accent: "#7C9EB2",
        accentSecondary: "#B87355",
        border: "#344250",
        success: "#76B692",
        warning: "#D2A64C",
        danger: "#E17B71",
        wheel: ["#D0A34A", "#334C60", "#A9664C", "#718B9B", "#7A6740"],
      },
    },
    prizes: [
      { id: "beard_detail", name: "Perfilado de barba sin cargo", probability: 30 },
      { id: "discount_15", name: "15% en tu próximo corte", probability: 30 },
      { id: "hair_treatment", name: "Tratamiento capilar premium", probability: 20 },
      { id: "product", name: "Producto de styling de regalo", probability: 15 },
      { id: "atlas_ritual", name: "Ritual Atlas completo", probability: 5 },
    ],
  },
];

export function getMerchantBySlug(slug: string): Merchant | undefined {
  return merchants.find((merchant) => merchant.slug === slug);
}

export function getMerchantById(id: string): Merchant | undefined {
  return merchants.find((merchant) => merchant.id === id);
}
